"""
McGill Faculty of Arts & Science – Degree Requirements Seed Data
Source: McGill eCalendar 2024-2025 and Course Catalogue
https://www.mcgill.ca/study/2024-2025/faculties/basc/undergraduate/programs
https://coursecatalogue.mcgill.ca/en/undergraduate/arts-science/

This file covers the B.A. & Sc. (Bachelor of Arts and Science) degree, which is
jointly offered by the Faculties of Arts and Science. It includes:
  - The three unique Interfaculty Programs (Cognitive Science, Environment, Sustainability)
  - Their corresponding Honours extensions

Accuracy notes:
  - Verified against McGill eCalendar 2024-2025 and Course Catalogue
  - Always cross-check with current catalogue before academic decisions
  - B.A. & Sc. students must also complete an approved minor/minor concentration
  - All programs require completion of the B.A. & Sc. Foundation Program
  - Environment program area structure verified April 2026 against eCalendar
    (8 official content areas, not the 9 areas in the prior version)
  - SSS "Biophysical" block is choose-5-from-5, not all-required
"""

ARTS_SCIENCE_PROGRAMS = [
  {
    "program_key": 'cogs_interfaculty_basc',
    "name": 'Cognitive Science Interfaculty Program (B.A. & Sc.) (54 credits)',
    "program_type": 'major',
    "faculty": 'Faculty of Arts & Science',
    "total_credits": 54,
    "description": 'The B.A. & Sc. Interfaculty Program Cognitive Science explores the multidisciplinary study of cognition in humans and machines. The principles of intelligence and thought, the mind and learning, and the development of intelligent devices.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts-science/programs/cognitive-science/cognitive-science-interfaculty-program-basc/',
    "blocks": [
      {
        "block_key": 'cogs_interfaculty_basc_required',
        "title": 'Required Course (3 credits)',
        "block_type": 'required',
        "credits_needed": 3,
        "sort_order": 1,
        "courses": [
          {
            "subject": 'PSYC',
            "catalog": '213',
            "title": 'Cognition',
            "credits": 3.0,
            "is_required": True,
          },
        ],
      },
      {
        "block_key": 'cogs_interfaculty_basc_core_complementary',
        "title": 'Core Complementary Courses (21 credits)',
        "block_type": 'multi_group',
        "credits_needed": 21,
        "notes": '3 credits from each of the following six subject area groups: Logic, Statistics, Computer Science, Linguistics, Philosophy, Neuroscience.',
        "sort_order": 2,
      },
      {
        "block_key": 'cogs_interfaculty_basc_core_logic',
        "title": 'Logic Courses (3 credits)',
        "block_type": 'group',
        "group_name": 'Logic',
        "credits_needed": 3,
        "notes": '3 credits from the following logic courses.',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'COMP',
            "catalog": '230',
            "title": 'Logic and Computability',
            "credits": 3.0,
            "choose_from_group": 'Logic',
          },
          {
            "subject": 'MATH',
            "catalog": '318',
            "title": 'Mathematical Logic',
            "credits": 3.0,
            "choose_from_group": 'Logic',
          },
          {
            "subject": 'PHIL',
            "catalog": '210',
            "title": 'Introduction to Deductive Logic 1',
            "credits": 3.0,
            "choose_from_group": 'Logic',
          },
        ],
      },
      {
        "block_key": 'cogs_interfaculty_basc_core_statistics',
        "title": 'Statistics Courses (3 credits)',
        "block_type": 'group',
        "group_name": 'Statistics',
        "credits_needed": 3,
        "notes": '3 credits from the following statistics courses.',
        "sort_order": 4,
        "courses": [
          {
            "subject": 'MATH',
            "catalog": '203',
            "title": 'Principles of Statistics 1',
            "credits": 3.0,
            "choose_from_group": 'Statistics',
          },
          {
            "subject": 'MATH',
            "catalog": '323',
            "title": 'Probability',
            "credits": 3.0,
            "choose_from_group": 'Statistics',
          },
          {
            "subject": 'PSYC',
            "catalog": '204',
            "title": 'Introduction to Psychological Statistics',
            "credits": 3.0,
            "choose_from_group": 'Statistics',
          },
        ],
      },
      {
        "block_key": 'cogs_interfaculty_basc_core_cs',
        "title": 'Computer Science Courses (3 credits)',
        "block_type": 'group',
        "group_name": 'Computer Science (Core)',
        "credits_needed": 3,
        "notes": '3 credits from the following computer science courses.',
        "sort_order": 5,
        "courses": [
          {
            "subject": 'COMP',
            "catalog": '202',
            "title": 'Foundations of Programming',
            "credits": 3.0,
            "choose_from_group": 'Computer Science (Core)',
          },
          {
            "subject": 'COMP',
            "catalog": '204',
            "title": 'Computer Programming for Life Sciences',
            "credits": 3.0,
            "choose_from_group": 'Computer Science (Core)',
          },
          {
            "subject": 'COMP',
            "catalog": '250',
            "title": 'Introduction to Computer Science',
            "credits": 3.0,
            "choose_from_group": 'Computer Science (Core)',
          },
        ],
      },
      {
        "block_key": 'cogs_interfaculty_basc_core_linguistics',
        "title": 'Linguistics Courses (3 credits)',
        "block_type": 'group',
        "group_name": 'Linguistics (Core)',
        "credits_needed": 3,
        "notes": '3 credits from the following linguistics courses.',
        "sort_order": 6,
        "courses": [
          {
            "subject": 'LING',
            "catalog": '201',
            "title": 'Introduction to Linguistics',
            "credits": 3.0,
            "choose_from_group": 'Linguistics (Core)',
          },
          {
            "subject": 'LING',
            "catalog": '210',
            "title": 'Introduction to Speech Science',
            "credits": 3.0,
            "choose_from_group": 'Linguistics (Core)',
          },
          {
            "subject": 'LING',
            "catalog": '260',
            "title": 'Meaning in Language',
            "credits": 3.0,
            "choose_from_group": 'Linguistics (Core)',
          },
        ],
      },
      {
        "block_key": 'cogs_interfaculty_basc_core_philosophy',
        "title": 'Philosophy Courses (3 credits)',
        "block_type": 'group',
        "group_name": 'Philosophy (Core)',
        "credits_needed": 3,
        "notes": '3 credits from the following philosophy courses.',
        "sort_order": 7,
        "courses": [
          {
            "subject": 'PHIL',
            "catalog": '200',
            "title": 'Introduction to Philosophy 1',
            "credits": 3.0,
            "choose_from_group": 'Philosophy (Core)',
            "notes": 'Not currently offered as of 2026-2027.',
          },
          {
            "subject": 'PHIL',
            "catalog": '201',
            "title": 'Introduction to Philosophy 2',
            "credits": 3.0,
            "choose_from_group": 'Philosophy (Core)',
          },
          {
            "subject": 'PHIL',
            "catalog": '203',
            "title": 'Introduction to Artificial Intelligence Ethics',
            "credits": 3.0,
            "choose_from_group": 'Philosophy (Core)',
          },
          {
            "subject": 'PHIL',
            "catalog": '221',
            "title": 'Introduction to History and Philosophy of Science 2',
            "credits": 3.0,
            "choose_from_group": 'Philosophy (Core)',
          },
        ],
      },
      {
        "block_key": 'cogs_interfaculty_basc_core_neuroscience',
        "title": 'Neuroscience Courses (3 credits)',
        "block_type": 'group',
        "group_name": 'Neuroscience (Core)',
        "credits_needed": 3,
        "notes": '3 credits from the following neuroscience courses.',
        "sort_order": 8,
        "courses": [
          {
            "subject": 'NSCI',
            "catalog": '200',
            "title": 'Introduction to Neuroscience 1',
            "credits": 3.0,
            "choose_from_group": 'Neuroscience (Core)',
          },
          {
            "subject": 'PHGY',
            "catalog": '209',
            "title": 'Mammalian Physiology 1',
            "credits": 3.0,
            "choose_from_group": 'Neuroscience (Core)',
          },
          {
            "subject": 'PSYC',
            "catalog": '211',
            "title": 'Introductory Behavioural Neuroscience',
            "credits": 3.0,
            "choose_from_group": 'Neuroscience (Core)',
          },
        ],
      },
      {
        "block_key": 'cogs_interfaculty_basc_complementary',
        "title": 'Complementary Courses (33 credits)',
        "block_type": 'multi_group',
        "credits_needed": 33,
        "notes": '30 credits selected as follows: 18 credits from ONE of the five lists (Computer Science, Linguistics, Neuroscience, Philosophy, or Psychology); 15 credits from any of the five lists. Of the 33 credits, 15 must be at the 400 level or higher. WARNING: The catalogue page was truncated. Only partial course listings for the Computer Science stream are available (COMP 206, COMP 250, COMP 251 cut off). The full lists for all five streams and the complete 400-level course requirements could not be extracted. Advisors must verify the complete stream course lists from the live catalogue.',
        "sort_order": 9,
        "courses": [
          {
            "subject": 'COMP',
            "catalog": '206',
            "title": 'Introduction to Software Systems',
            "credits": 3.0,
            "choose_from_group": 'Computer Science',
            "notes": 'Part of Computer Science stream in Complementary Courses. Page truncated — full stream lists not available.',
          },
          {
            "subject": 'COMP',
            "catalog": '250',
            "title": 'Introduction to Computer Science',
            "credits": 3.0,
            "choose_from_group": 'Computer Science',
            "notes": 'Part of Computer Science stream in Complementary Courses. Also appears in Core Complementary CS group.',
          },
          {
            "subject": 'COMP',
            "catalog": '251',
            "title": 'Algorithms and Data Structures',
            "credits": 3.0,
            "choose_from_group": 'Computer Science',
            "notes": 'Part of Computer Science stream in Complementary Courses. Page truncated — course description and remaining stream lists incomplete.',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'cogs_honours_basc',
    "name": 'Cognitive Science Honours (B.A. & Sc.) (60 credits)',
    "program_type": 'honours',
    "faculty": 'Faculty of Science',
    "total_credits": 60,
    "description": 'The Honours Cognitive Science, restricted to students in the B.A. & Sc., is an extension of the Interfaculty program and offers students an opportunity to undertake a research project in close association with professors in their main Arts and Science focus areas. To receive an Honours degree, students must achieve a minimum overall program GPA of 3.3 at graduation and attain a grade of B+ (3.3) or better in COGS 444 Honours Research. Students must complete both the 60-credit Honours program and an approved minor in the Faculties of Arts or of Science. B.A. & Sc. students must take at least 21 credits in Arts and 21 credits in Science across their interfaculty program and their minor.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts-science/programs/cognitive-science/cognitive-science-honours-basc/',
    "blocks": [
      {
        "block_key": 'cogs_honours_basc_required',
        "title": 'Required Courses (9 credits)',
        "block_type": 'required',
        "credits_needed": 9,
        "notes": 'Students must achieve a minimum program GPA of 3.3 and a grade of B+ (3.3) or better in COGS 444 to receive Honours degree.',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'COGS',
            "catalog": '444',
            "title": 'Honours Research',
            "credits": 6.0,
            "is_required": True,
            "notes": 'Honours research project. Supervised research in main Arts and Science focus areas.',
          },
          {
            "subject": 'NSCI',
            "catalog": '201',
            "title": 'Introduction to Neuroscience 2',
            "credits": 3.0,
            "is_required": True,
            "notes": 'An introduction to how the nervous system acquires and integrates information and uses it to produce behaviour.',
          },
        ],
      },
      {
        "block_key": 'cogs_honours_basc_core_complementary',
        "title": 'Core Complementary Courses (21 credits)',
        "block_type": 'pool_group',
        "credits_needed": 21,
        "notes": '6 groups of 3 credits each (one course per group). Choose one course from each of the six categories: Logic, Statistics, Computer Science, Linguistics, Philosophy, and Neuroscience/Psychology.',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'COMP',
            "catalog": '230',
            "title": 'Logic and Computability',
            "credits": 3.0,
            "choose_from_group": 'Logic',
          },
          {
            "subject": 'MATH',
            "catalog": '318',
            "title": 'Mathematical Logic',
            "credits": 3.0,
            "choose_from_group": 'Logic',
          },
          {
            "subject": 'PHIL',
            "catalog": '210',
            "title": 'Introduction to Deductive Logic 1',
            "credits": 3.0,
            "choose_from_group": 'Logic',
          },
          {
            "subject": 'MATH',
            "catalog": '203',
            "title": 'Principles of Statistics 1',
            "credits": 3.0,
            "choose_from_group": 'Statistics',
          },
          {
            "subject": 'MATH',
            "catalog": '323',
            "title": 'Probability',
            "credits": 3.0,
            "choose_from_group": 'Statistics',
          },
          {
            "subject": 'PSYC',
            "catalog": '204',
            "title": 'Introduction to Psychological Statistics',
            "credits": 3.0,
            "choose_from_group": 'Statistics',
          },
          {
            "subject": 'COMP',
            "catalog": '202',
            "title": 'Foundations of Programming',
            "credits": 3.0,
            "choose_from_group": 'Computer Science',
          },
          {
            "subject": 'COMP',
            "catalog": '204',
            "title": 'Computer Programming for Life Sciences',
            "credits": 3.0,
            "choose_from_group": 'Computer Science',
          },
          {
            "subject": 'COMP',
            "catalog": '250',
            "title": 'Introduction to Computer Science',
            "credits": 3.0,
            "choose_from_group": 'Computer Science',
          },
          {
            "subject": 'LING',
            "catalog": '201',
            "title": 'Introduction to Linguistics',
            "credits": 3.0,
            "choose_from_group": 'Linguistics',
          },
          {
            "subject": 'LING',
            "catalog": '210',
            "title": 'Introduction to Speech Science',
            "credits": 3.0,
            "choose_from_group": 'Linguistics',
          },
          {
            "subject": 'LING',
            "catalog": '260',
            "title": 'Meaning in Language',
            "credits": 3.0,
            "choose_from_group": 'Linguistics',
          },
          {
            "subject": 'PHIL',
            "catalog": '200',
            "title": 'Introduction to Philosophy 1',
            "credits": 3.0,
            "choose_from_group": 'Philosophy',
            "notes": 'Not currently offered 2026-2027.',
          },
          {
            "subject": 'PHIL',
            "catalog": '201',
            "title": 'Introduction to Philosophy 2',
            "credits": 3.0,
            "choose_from_group": 'Philosophy',
          },
          {
            "subject": 'PHIL',
            "catalog": '221',
            "title": 'Introduction to History and Philosophy of Science 2',
            "credits": 3.0,
            "choose_from_group": 'Philosophy',
          },
          {
            "subject": 'NSCI',
            "catalog": '200',
            "title": 'Introduction to Neuroscience 1',
            "credits": 3.0,
            "choose_from_group": 'Neuroscience/Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '211',
            "title": 'Introductory Behavioural Neuroscience',
            "credits": 3.0,
            "choose_from_group": 'Neuroscience/Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '212',
            "title": 'Perception',
            "credits": 3.0,
            "choose_from_group": 'Neuroscience/Psychology',
            "notes": 'Not currently offered 2026-2027.',
          },
          {
            "subject": 'PSYC',
            "catalog": '213',
            "title": 'Cognition',
            "credits": 3.0,
            "choose_from_group": 'Neuroscience/Psychology',
          },
        ],
      },
      {
        "block_key": 'cogs_honours_basc_complementary_cs',
        "title": 'Complementary Courses - Computer Science (18 credits minimum)',
        "block_type": 'choose_credits',
        "group_name": 'Computer Science',
        "credits_needed": 18,
        "notes": '18 credits from Computer Science list. Must include 15 credits at 400-level or higher across all 30 complementary credits.',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'COMP',
            "catalog": '206',
            "title": 'Introduction to Software Systems',
            "credits": 3.0,
          },
          {
            "subject": 'COMP',
            "catalog": '250',
            "title": 'Introduction to Computer Science',
            "credits": 3.0,
          },
          {
            "subject": 'COMP',
            "catalog": '251',
            "title": 'Algorithms and Data Structures',
            "credits": 3.0,
          },
          {
            "subject": 'COMP',
            "catalog": '280',
            "title": 'History and Philosophy of Computing',
            "credits": 3.0,
            "notes": 'Not currently offered 2026-2027.',
          },
          {
            "subject": 'COMP',
            "catalog": '302',
            "title": 'Programming Languages and Paradigms',
            "credits": 3.0,
          },
          {
            "subject": 'COMP',
            "catalog": '330',
            "title": 'Theory of Computation',
            "credits": 3.0,
          },
          {
            "subject": 'COMP',
            "catalog": '345',
            "title": 'From Natural Language to Data Science',
            "credits": 3.0,
          },
          {
            "subject": 'COMP',
            "catalog": '360',
            "title": 'Algorithm Design',
            "credits": 3.0,
          },
          {
            "subject": 'COMP',
            "catalog": '400',
            "title": 'Project in Computer Science',
            "credits": 4.0,
            "notes": '400-level course.',
          },
          {
            "subject": 'COMP',
            "catalog": '409',
            "title": 'Concurrent Programming',
            "credits": 3.0,
            "notes": '400-level course.',
          },
          {
            "subject": 'COMP',
            "catalog": '417',
            "title": 'Introduction Robotics and Intelligent Systems',
            "credits": 3.0,
            "notes": '400-level course.',
          },
          {
            "subject": 'COMP',
            "catalog": '421',
            "title": 'Database Systems',
            "credits": 3.0,
            "notes": '400-level course.',
          },
          {
            "subject": 'COMP',
            "catalog": '424',
            "title": 'Artificial Intelligence',
            "credits": 3.0,
            "notes": '400-level course.',
          },
          {
            "subject": 'COMP',
            "catalog": '445',
            "title": 'Computational Linguistics',
            "credits": 3.0,
            "notes": '400-level course.',
          },
          {
            "subject": 'COMP',
            "catalog": '451',
            "title": 'Fundamentals of Machine Learning',
            "credits": 3.0,
            "notes": '400-level course. Not currently offered 2026-2027.',
          },
          {
            "subject": 'COMP',
            "catalog": '523',
            "title": 'Language-based Security',
            "credits": 3.0,
            "notes": '500-level course. Not currently offered 2026-2027.',
          },
          {
            "subject": 'COMP',
            "catalog": '527',
            "title": 'Logic and Computation',
            "credits": 3.0,
            "notes": '500-level course. Not currently offered 2026-2027.',
          },
          {
            "subject": 'COMP',
            "catalog": '531',
            "title": 'Advanced Theory of Computation',
            "credits": 3.0,
            "notes": '500-level course.',
          },
          {
            "subject": 'COMP',
            "catalog": '545',
            "title": 'Natural Language Understanding with Deep Learning',
            "credits": 4.0,
            "notes": '500-level course. Not currently offered 2026-2027.',
          },
          {
            "subject": 'COMP',
            "catalog": '546',
            "title": 'Computational Perception',
            "credits": 4.0,
            "notes": '500-level course. Page appears truncated; full course list may continue.',
          },
        ],
      },
      {
        "block_key": 'cogs_honours_basc_complementary_linguistics',
        "title": 'Complementary Courses - Linguistics',
        "block_type": 'choose_credits',
        "group_name": 'Linguistics',
        "notes": 'Linguistics courses available for complementary electives. 18 credits from one list required; this list can fulfill that requirement or contribute to the 12 discretionary credits.',
        "sort_order": 4,
      },
      {
        "block_key": 'cogs_honours_basc_complementary_neuroscience',
        "title": 'Complementary Courses - Neuroscience',
        "block_type": 'choose_credits',
        "group_name": 'Neuroscience',
        "notes": 'Neuroscience courses available for complementary electives. 18 credits from one list required; this list can fulfill that requirement or contribute to the 12 discretionary credits.',
        "sort_order": 5,
      },
      {
        "block_key": 'cogs_honours_basc_complementary_philosophy',
        "title": 'Complementary Courses - Philosophy',
        "block_type": 'choose_credits',
        "group_name": 'Philosophy',
        "notes": 'Philosophy courses available for complementary electives. 18 credits from one list required; this list can fulfill that requirement or contribute to the 12 discretionary credits.',
        "sort_order": 6,
      },
      {
        "block_key": 'cogs_honours_basc_complementary_psychology',
        "title": 'Complementary Courses - Psychology',
        "block_type": 'choose_credits',
        "group_name": 'Psychology',
        "notes": 'Psychology courses available for complementary electives. 18 credits from one list required; this list can fulfill that requirement or contribute to the 12 discretionary credits.',
        "sort_order": 7,
      },
    ],
  },
  {
    "program_key": 'sss_interfaculty_basc',
    "name": 'Sustainability, Science and Society Interfaculty Program (B.A. & Sc.) (54 credits)',
    "program_type": 'major',
    "faculty": 'Faculty of Arts & Science',
    "total_credits": 54,
    "description": 'The B.A. & Sc. Interfaculty Program in Sustainability, Science and Society focuses on the interdisciplinary and integrative knowledge and skills required to effectively understand and address challenges in transitioning to a sustainable future. The program is built on three pillars: (1) Science and Technology – biophysical basis of current challenges; (2) Economics, Policy, and Governance – how to make the sustainability transition; (3) Ethics, Equity, and Justice – why we need change and related equity issues. Offered in collaboration with the Bieler School of Environment.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts-science/programs/sustainability-science-society/sustainability-science-society-interfaculty-program-basc/',
    "blocks": [
      {
        "block_key": 'sss_foundations',
        "title": 'Foundations of Sustainability (Required)',
        "block_type": 'required',
        "credits_needed": 12,
        "constraint_notes": 'All four courses are required.',
        "notes": 'All four courses are required.',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'ENVR',
            "catalog": '201',
            "title": 'Society, Environment and Sustainability',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'GEOG',
            "catalog": '360',
            "title": 'Analyzing Sustainability',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'GEOG',
            "catalog": '401',
            "title": 'Socio-Environmental Systems: Theory and Simulation',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'GEOG',
            "catalog": '460',
            "title": 'Research in Sustainability',
            "credits": 3.0,
            "is_required": True,
          },
        ],
      },
      {
        "block_key": 'sss_biophysical',
        "title": 'Biophysical, Societal, Cultural, Institutional, and Ethical (Required)',
        "block_type": 'required',
        "credits_needed": 15,
        "constraint_notes": 'All five courses are required.',
        "notes": 'All five courses are required.',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'ENVR',
            "catalog": '200',
            "title": 'The Global Environment',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'ENVR',
            "catalog": '202',
            "title": 'The Evolving Earth',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'ENVR',
            "catalog": '203',
            "title": 'Knowledge, Ethics and Environment',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'GEOG',
            "catalog": '203',
            "title": 'Environmental Systems',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'GEOG',
            "catalog": '408',
            "title": 'Geography of Development',
            "credits": 3.0,
            "is_required": True,
          },
        ],
      },
      {
        "block_key": 'sss_comp_stats',
        "title": 'Complementary – Statistics (3 credits)',
        "block_type": 'choose_courses',
        "credits_needed": 3,
        "courses_needed": 1,
        "constraint_notes": 'Choose 3 credits from statistics courses.',
        "notes": 'Choose 3 credits from statistics courses.',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'AEMA',
            "catalog": '310',
            "title": 'Statistical Methods 1',
            "credits": 3.0,
          },
          {
            "subject": 'BIOL',
            "catalog": '373',
            "title": 'Biometry',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '202',
            "title": 'Statistics and Spatial Analysis',
            "credits": 3.0,
          },
          {
            "subject": 'MATH',
            "catalog": '203',
            "title": 'Principles of Statistics 1',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '204',
            "title": 'Introduction to Psychological Statistics',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'sss_comp_econ',
        "title": 'Complementary – Economics (3 credits)',
        "block_type": 'choose_courses',
        "credits_needed": 3,
        "courses_needed": 1,
        "constraint_notes": 'Choose 3 credits from economics courses.',
        "notes": 'Choose 3 credits from economics courses.',
        "sort_order": 4,
        "courses": [
          {
            "subject": 'AGEC',
            "catalog": '200',
            "title": 'Principles of Microeconomics',
            "credits": 3.0,
          },
          {
            "subject": 'AGEC',
            "catalog": '201',
            "title": 'Principles of Macroeconomics',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '208',
            "title": 'Microeconomic Analysis and Applications',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '209',
            "title": 'Macroeconomic Analysis and Applications',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '225',
            "title": 'Economics of the Environment',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '230D1',
            "title": 'Microeconomic Theory',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'sss_comp_business',
        "title": 'Complementary – Sustainability in Business (3 credits)',
        "block_type": 'choose_courses',
        "credits_needed": 3,
        "courses_needed": 1,
        "constraint_notes": 'Choose 3 credits from management/business courses.',
        "notes": 'Choose 3 credits from management/business courses.',
        "sort_order": 5,
        "courses": [
          {
            "subject": 'INSY',
            "catalog": '455',
            "title": 'Technology and Innovation for Sustainability',
            "credits": 3.0,
          },
          {
            "subject": 'MGCR',
            "catalog": '460',
            "title": 'Social Context of Business',
            "credits": 3.0,
          },
          {
            "subject": 'MGPO',
            "catalog": '440',
            "title": 'Strategies for Sustainability',
            "credits": 3.0,
          },
          {
            "subject": 'MGPO',
            "catalog": '475',
            "title": 'Strategies for Developing Countries',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'sss_area1_methods',
        "title": 'Area 1 – Methods: Observation, Analysis, Modelling, and Management',
        "block_type": 'group',
        "group_name": 'Area 1 – Methods',
        "constraint_notes": '18 additional credits from Areas 1, 2, and 3: at least 9 credits at the 300 level or higher, and at least 6 credits from EACH of the three areas.',
        "notes": '18 additional credits from Areas 1, 2, and 3: at least 9 credits at the 300 level or higher, and at least 6 credits from EACH of the three areas.',
        "sort_order": 6,
        "courses": [
          {
            "subject": 'ENVB',
            "catalog": '437',
            "title": 'Assessing Environmental Impact',
            "credits": 3.0,
          },
          {
            "subject": 'ENVB',
            "catalog": '529',
            "title": 'GIS for Natural Resource Management',
            "credits": 3.0,
            "notes": 'Or GEOG 201, but not both.',
          },
          {
            "subject": 'ESYS',
            "catalog": '301',
            "title": 'Earth System Modelling',
            "credits": 3.0,
          },
          {
            "subject": 'ESYS',
            "catalog": '500',
            "title": 'Collaborative Research Project',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '201',
            "title": 'Introductory Geo-Information Science',
            "credits": 3.0,
            "notes": 'Or ENVB 529, but not both.',
          },
          {
            "subject": 'GEOG',
            "catalog": '302',
            "title": 'Environmental Management 1',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '308',
            "title": 'Remote Sensing for Earth Observation',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '314',
            "title": 'Geospatial Analysis',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '333',
            "title": 'Introduction to Programming for Spatial Sciences',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '351',
            "title": 'Quantitative Methods',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '404',
            "title": 'Environmental Management 2',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '414',
            "title": 'Advanced Geospatial Analysis',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '495',
            "title": 'Field Studies – Physical Geography',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '509',
            "title": 'Qualitative Methods',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '512',
            "title": 'Advanced Quantitative Methods in Social Field Research',
            "credits": 3.0,
          },
          {
            "subject": 'URBP',
            "catalog": '506',
            "title": 'Environmental Policy and Planning',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'sss_area2a_society',
        "title": 'Area 2A – Society, Economics, and Policy',
        "block_type": 'group',
        "group_name": 'Area 2A – Society, Economics, and Policy',
        "constraint_notes": 'At least 3 credits from Area 2A.',
        "notes": 'At least 3 credits from Area 2A.',
        "sort_order": 7,
        "courses": [
          {
            "subject": 'AGEC',
            "catalog": '333',
            "title": 'Resource Economics',
            "credits": 3.0,
          },
          {
            "subject": 'AGEC',
            "catalog": '430',
            "title": 'Agriculture, Food and Resource Policy',
            "credits": 3.0,
          },
          {
            "subject": 'AGEC',
            "catalog": '442',
            "title": 'Economics of International Agricultural Development',
            "credits": 3.0,
          },
          {
            "subject": 'ANTH',
            "catalog": '206',
            "title": 'Environment and Culture',
            "credits": 3.0,
          },
          {
            "subject": 'ANTH',
            "catalog": '212',
            "title": 'Anthropology of Development',
            "credits": 3.0,
          },
          {
            "subject": 'ANTH',
            "catalog": '339',
            "title": 'Ecological Anthropology',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '313',
            "title": 'Economic Development 1',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '314',
            "title": 'Economic Development 2',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '326',
            "title": 'Ecological Economics',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '347',
            "title": 'Economics of Climate Change',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '405',
            "title": 'Natural Resource Economics',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '210',
            "title": 'Global Places and Peoples',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '216',
            "title": 'Geography of the World Economy',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '303',
            "title": 'Health Geography',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '310',
            "title": 'Development and Livelihoods',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '316',
            "title": 'Political Geography',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '409',
            "title": 'Geographies of Developing Asia',
            "credits": 3.0,
          },
          {
            "subject": 'HIST',
            "catalog": '292',
            "title": 'History and the Environment',
            "credits": 3.0,
          },
          {
            "subject": 'INDG',
            "catalog": '200',
            "title": 'Introduction to Indigenous Studies',
            "credits": 3.0,
          },
          {
            "subject": 'POLI',
            "catalog": '350',
            "title": 'Global Environmental Politics',
            "credits": 3.0,
          },
          {
            "subject": 'URBP',
            "catalog": '530',
            "title": 'Urban Infrastructure and Services in International Context',
            "credits": 3.0,
          },
          {
            "subject": 'URBP',
            "catalog": '553',
            "title": 'Urban Governance',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'sss_area2b_ethics',
        "title": 'Area 2B – Ethics and Equity',
        "block_type": 'group',
        "group_name": 'Area 2B – Ethics and Equity',
        "constraint_notes": 'At least 3 credits from Area 2B.',
        "notes": 'At least 3 credits from Area 2B.',
        "sort_order": 8,
        "courses": [
          {
            "subject": 'ENVR',
            "catalog": '400',
            "title": 'Environmental Thought',
            "credits": 3.0,
          },
          {
            "subject": 'MGPO',
            "catalog": '450',
            "title": 'Ethics in Management',
            "credits": 3.0,
          },
          {
            "subject": 'PHIL',
            "catalog": '349',
            "title": 'Environmental Philosophy',
            "credits": 3.0,
          },
          {
            "subject": 'RELG',
            "catalog": '270',
            "title": 'Religious Ethics and the Environment',
            "credits": 3.0,
          },
          {
            "subject": 'SOCI',
            "catalog": '325',
            "title": 'Sociology of Science',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'sss_area3_biophysical',
        "title": 'Area 3 – Sustainability and Biophysical Processes',
        "block_type": 'group',
        "group_name": 'Area 3 – Biophysical Processes',
        "constraint_notes": 'At least 6 credits from Area 3. BIOL 540 and ENVR 540 cannot both be taken; BREE 217 and GEOG 322 cannot both be taken.',
        "notes": 'At least 6 credits from Area 3. BIOL 540 and ENVR 540 cannot both be taken; BREE 217 and GEOG 322 cannot both be taken.',
        "sort_order": 9,
        "courses": [
          {
            "subject": 'ATOC',
            "catalog": '214',
            "title": 'Introduction: Physics of the Atmosphere',
            "credits": 3.0,
          },
          {
            "subject": 'ATOC',
            "catalog": '215',
            "title": 'Oceans, Weather and Climate',
            "credits": 3.0,
          },
          {
            "subject": 'BIOL',
            "catalog": '308',
            "title": 'Ecological Dynamics',
            "credits": 3.0,
          },
          {
            "subject": 'BIOL',
            "catalog": '310',
            "title": 'Biodiversity and Ecosystems',
            "credits": 3.0,
          },
          {
            "subject": 'BIOL',
            "catalog": '465',
            "title": 'Conservation Biology',
            "credits": 3.0,
          },
          {
            "subject": 'BIOL',
            "catalog": '540',
            "title": 'Ecology of Species Invasions',
            "credits": 3.0,
            "notes": 'Or ENVR 540, not both.',
          },
          {
            "subject": 'BREE',
            "catalog": '217',
            "title": 'Hydrology and Water Resources',
            "credits": 3.0,
            "notes": 'Or GEOG 322, not both.',
          },
          {
            "subject": 'CHEM',
            "catalog": '462',
            "title": 'Green Chemistry',
            "credits": 3.0,
          },
          {
            "subject": 'ENVB',
            "catalog": '305',
            "title": 'Population and Community Ecology',
            "credits": 3.0,
          },
          {
            "subject": 'ENVB',
            "catalog": '410',
            "title": 'Ecosystem Ecology',
            "credits": 3.0,
          },
          {
            "subject": 'ENVR',
            "catalog": '540',
            "title": 'Ecology of Species Invasions',
            "credits": 3.0,
            "notes": 'Or BIOL 540, not both.',
          },
          {
            "subject": 'ESYS',
            "catalog": '200',
            "title": 'Earth-System Interactions',
            "credits": 3.0,
          },
          {
            "subject": 'ESYS',
            "catalog": '300',
            "title": 'Earth Data Analysis',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '221',
            "title": 'Environment and Health',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '272',
            "title": "Earth's Changing Surface",
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '305',
            "title": 'Soils and Environment',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '321',
            "title": 'Climatic Environments',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '322',
            "title": 'Environmental Hydrology',
            "credits": 3.0,
            "notes": 'Or BREE 217, not both.',
          },
          {
            "subject": 'GEOG',
            "catalog": '372',
            "title": 'Running Water Environments',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '403',
            "title": 'Global Health and Environmental Change',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '438',
            "title": 'Sand in the Anthropocene',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '470',
            "title": 'Wetlands',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '530',
            "title": 'Global Land and Water Resources',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '555',
            "title": 'Ecological Restoration',
            "credits": 3.0,
          },
          {
            "subject": 'NRSC',
            "catalog": '333',
            "title": 'Pollution and Bioremediation',
            "credits": 3.0,
          },
        ],
      },
    ],
  },
  {
    "program_key": 'sss_honours_basc',
    "name": 'Sustainability, Science and Society Honours (B.A. & Sc.) (60 credits)',
    "program_type": 'honours',
    "faculty": 'Faculty of Arts & Science',
    "total_credits": 60,
    "description": "The grand challenge of the 21st century is sustainable well-being – improving human well-being while maintaining the Earth's life-support systems. This B.A. & Sc. Honours program provides the interdisciplinary knowledge and skills to address this challenge across three pillars: Science and Technology, Economics/Policy/Governance, and Ethics/Equity/Justice. The Honours extension adds 6 credits of supervised research (ENVR 495 Honours Research) to the 54-credit Interfaculty Program requirements. Minimum program GPA of 3.3 required at graduation.",
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts-science/programs/sustainability-science-society/sustainability-science-society-honours-basc/',
    "blocks": [
      {
        "block_key": 'sss_honours_basc_foundations',
        "title": 'Foundations of Sustainability (12 credits)',
        "block_type": 'required',
        "credits_needed": 12,
        "sort_order": 1,
        "courses": [
          {
            "subject": 'ENVR',
            "catalog": '201',
            "title": 'Society, Environment and Sustainability',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'GEOG',
            "catalog": '360',
            "title": 'Analyzing Sustainability',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'GEOG',
            "catalog": '401',
            "title": 'Socio-Environmental Systems: Theory and Simulation',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'GEOG',
            "catalog": '460',
            "title": 'Research in Sustainability',
            "credits": 3.0,
            "is_required": True,
          },
        ],
      },
      {
        "block_key": 'sss_honours_basc_honours_research',
        "title": 'Honours Required Courses (6 credits)',
        "block_type": 'required',
        "credits_needed": 6,
        "notes": 'Students must take either ENVR 495D1 and ENVR 495D2 (consecutive terms) OR ENVR 495N1 and ENVR 495N2 (non-consecutive terms). Students must earn B (3.0) or higher in Honours Research courses. Minimum program GPA of 3.3 required to enter Honours program and maintain Honours status at graduation.',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'ENVR',
            "catalog": '495D1',
            "title": 'Honours Research',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Preparation of an honours thesis. Consecutive term option.',
          },
          {
            "subject": 'ENVR',
            "catalog": '495D2',
            "title": 'Honours Research',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Preparation of an honours thesis. Consecutive term option (paired with D1).',
          },
          {
            "subject": 'ENVR',
            "catalog": '495N1',
            "title": 'Honours Research',
            "credits": 3.0,
            "notes": 'Preparation of an honours thesis. Non-consecutive term option (alternative to D1).',
          },
          {
            "subject": 'ENVR',
            "catalog": '495N2',
            "title": 'Honours Research',
            "credits": 3.0,
            "notes": 'Preparation of an honours thesis. Non-consecutive term option (paired with N1).',
          },
        ],
      },
      {
        "block_key": 'sss_honours_basc_biophysical_societal',
        "title": 'Biophysical, Societal, Cultural, Institutional, and Ethical (15 credits)',
        "block_type": 'required',
        "credits_needed": 15,
        "sort_order": 3,
        "courses": [
          {
            "subject": 'ENVR',
            "catalog": '200',
            "title": 'The Global Environment',
            "credits": 3.0,
          },
          {
            "subject": 'ENVR',
            "catalog": '202',
            "title": 'The Evolving Earth',
            "credits": 3.0,
          },
          {
            "subject": 'ENVR',
            "catalog": '203',
            "title": 'Knowledge, Ethics and Environment',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '203',
            "title": 'Environmental Systems',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '408',
            "title": 'Geography of Development',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'sss_honours_basc_statistics',
        "title": 'Statistics (3 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 3,
        "notes": 'Choose 3 credits from the following.',
        "sort_order": 4,
        "courses": [
          {
            "subject": 'AEMA',
            "catalog": '310',
            "title": 'Statistical Methods 1',
            "credits": 3.0,
          },
          {
            "subject": 'BIOL',
            "catalog": '373',
            "title": 'Biometry',
            "credits": 3.0,
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'GEOG',
            "catalog": '202',
            "title": 'Statistics and Spatial Analysis',
            "credits": 3.0,
          },
          {
            "subject": 'MATH',
            "catalog": '203',
            "title": 'Principles of Statistics 1',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '204',
            "title": 'Introduction to Psychological Statistics',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'sss_honours_basc_economics',
        "title": 'Economics (3 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 3,
        "notes": 'Choose 3 credits from the following.',
        "sort_order": 5,
        "courses": [
          {
            "subject": 'AGEC',
            "catalog": '200',
            "title": 'Principles of Microeconomics',
            "credits": 3.0,
          },
          {
            "subject": 'AGEC',
            "catalog": '201',
            "title": 'Principles of Macroeconomics',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '208',
            "title": 'Microeconomic Analysis and Applications',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '209',
            "title": 'Macroeconomic Analysis and Applications',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '225',
            "title": 'Economics of the Environment',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '230D1',
            "title": 'Microeconomic Theory',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '230D2',
            "title": 'Microeconomic Theory',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'sss_honours_basc_sustainability_business',
        "title": 'Sustainability in Business (3 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 3,
        "notes": 'Choose 3 credits of Management from the following.',
        "sort_order": 6,
        "courses": [
          {
            "subject": 'INSY',
            "catalog": '455',
            "title": 'Technology and Innovation for Sustainability',
            "credits": 3.0,
          },
          {
            "subject": 'MGCR',
            "catalog": '460',
            "title": 'Social Context of Business',
            "credits": 3.0,
          },
          {
            "subject": 'MGPO',
            "catalog": '440',
            "title": 'Strategies for Sustainability',
            "credits": 3.0,
          },
          {
            "subject": 'MGPO',
            "catalog": '475',
            "title": 'Strategies for Developing Countries',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'sss_honours_basc_area1_methods',
        "title": 'Area 1: Methods: Observation, Analysis, Modelling, and Management (variable credits)',
        "block_type": 'choose_credits',
        "group_name": 'Area 1',
        "notes": '18 additional credits of complementary courses chosen from three areas (1, 2, 3). At least 9 credits must be at 300 level or higher; students must choose at least 6 credits from EACH area (1, 2, and 3). This block represents Area 1 options only.',
        "sort_order": 7,
        "courses": [
          {
            "subject": 'ENVB',
            "catalog": '437',
            "title": 'Assessing Environmental Impact',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'ENVB',
            "catalog": '529',
            "title": 'GIS for Natural Resource Management',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'ESYS',
            "catalog": '301',
            "title": 'Earth System Modelling',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'ESYS',
            "catalog": '500',
            "title": 'Collaborative Research Project',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'GEOG',
            "catalog": '201',
            "title": 'Introductory Geo-Information Science',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'GEOG',
            "catalog": '302',
            "title": 'Environmental Management 1',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'GEOG',
            "catalog": '308',
            "title": 'Remote Sensing for Earth Observation',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'GEOG',
            "catalog": '314',
            "title": 'Geospatial Analysis',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'GEOG',
            "catalog": '333',
            "title": 'Introduction to Programming for Spatial Sciences',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'GEOG',
            "catalog": '351',
            "title": 'Quantitative Methods',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'GEOG',
            "catalog": '398',
            "title": 'Field Studies in Human Geography',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
            "notes": 'Not currently offered.',
          },
        ],
      },
      {
        "block_key": 'sss_honours_basc_area2_3_placeholder',
        "title": 'Areas 2 & 3: Courses (variable credits)',
        "block_type": 'choose_credits',
        "group_name": 'Areas 2-3',
        "notes": 'Students must choose at least 6 credits from Area 2 and at least 6 credits from Area 3 (total 18 credits from all three areas, with at least 9 at 300-level or higher). Area 2 and Area 3 course lists not provided in the source text.',
        "sort_order": 8,
      },
    ],
  },
  {
    "program_key": 'environment_interfaculty_basc',
    "name": 'Environment Interfaculty Program (B.A. & Sc.) (54 credits)',
    "program_type": 'major',
    "faculty": 'Faculty of Arts & Science',
    "total_credits": 54,
    "description": 'The B.A. & Sc. Interfaculty Program in Environment focuses on the myriad of environmental problems faced by society today. The program offers a great degree of flexibility and can provide both broad liberal arts/science training and specific in-depth focus on particular areas of interest. Students are required to take a maximum of 21 credits at the 200 level and a minimum of 12 credits at the 400 level or higher. Students must complete at least 21 credits in Arts and at least 21 in Science across their interfaculty program and minor. ENVR courses count toward both Arts and Science credit requirements.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts-science/programs/environment/interfaculty-program-environment-basc/',
    "blocks": [
      {
        "block_key": 'environment_interfaculty_basc_required',
        "title": 'Required Courses (18 credits)',
        "block_type": 'required',
        "credits_needed": 18,
        "notes": "Core required courses are taught at both McGill's Downtown campus and at the Macdonald campus in Sainte-Anne-de-Bellevue. Register in Section 001 for Downtown campus, Section 051 for Macdonald campus.",
        "sort_order": 1,
        "courses": [
          {
            "subject": 'ENVR',
            "catalog": '200',
            "title": 'The Global Environment',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'ENVR',
            "catalog": '201',
            "title": 'Society, Environment and Sustainability',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'ENVR',
            "catalog": '202',
            "title": 'The Evolving Earth',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'ENVR',
            "catalog": '203',
            "title": 'Knowledge, Ethics and Environment',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'ENVR',
            "catalog": '301',
            "title": 'Environmental Research Design',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'ENVR',
            "catalog": '400',
            "title": 'Environmental Thought',
            "credits": 3.0,
            "is_required": True,
          },
        ],
      },
      {
        "block_key": 'environment_interfaculty_basc_senior_research',
        "title": 'Senior Research Project',
        "block_type": 'choose_courses',
        "courses_needed": 1,
        "notes": 'Only 3 credits will be applied to the program; extra credits will count as electives.',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'AEBI',
            "catalog": '427',
            "title": 'Barbados Interdisciplinary Project',
            "credits": 6.0,
          },
          {
            "subject": 'ENVR',
            "catalog": '401',
            "title": 'Environmental Research',
            "credits": 3.0,
          },
          {
            "subject": 'ENVR',
            "catalog": '451',
            "title": 'Research in Panama',
            "credits": 6.0,
          },
          {
            "subject": 'FSCI',
            "catalog": '444',
            "title": 'Barbados Research Project',
            "credits": 6.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '451',
            "title": 'Research in Society and Development in Africa',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'environment_interfaculty_basc_statistics',
        "title": 'Statistics',
        "block_type": 'choose_courses',
        "credits_needed": 3,
        "courses_needed": 1,
        "sort_order": 3,
        "courses": [
          {
            "subject": 'AEMA',
            "catalog": '310',
            "title": 'Statistical Methods 1',
            "credits": 3.0,
          },
          {
            "subject": 'GEOG',
            "catalog": '202',
            "title": 'Statistics and Spatial Analysis',
            "credits": 3.0,
          },
          {
            "subject": 'MATH',
            "catalog": '203',
            "title": 'Principles of Statistics 1',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '204',
            "title": 'Introduction to Psychological Statistics',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'environment_interfaculty_basc_area1',
        "title": 'Area 1: Population, Community, and Ecosystem Ecology',
        "block_type": 'group',
        "group_name": 'Area 1',
        "notes": 'BIOL 308 and ENVB 305 are mutually exclusive; you may take one or the other but not both.',
        "sort_order": 4,
        "courses": [
          {
            "subject": 'BIOL',
            "catalog": '308',
            "title": 'Ecological Dynamics',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
            "notes": 'Mutually exclusive with ENVB 305',
          },
          {
            "subject": 'BIOL',
            "catalog": '342',
            "title": 'Global Change Biology of Aquatic Ecosystems',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'BIOL',
            "catalog": '432',
            "title": 'Limnology',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'BIOL',
            "catalog": '441',
            "title": 'Biological Oceanography',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'BIOL',
            "catalog": '540',
            "title": 'Ecology of Species Invasions',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'ENVB',
            "catalog": '305',
            "title": 'Population and Community Ecology',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
            "notes": 'Mutually exclusive with BIOL 308',
          },
          {
            "subject": 'ENVB',
            "catalog": '410',
            "title": 'Ecosystem Ecology',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'ENVB',
            "catalog": '500',
            "title": 'Advanced Topics in Ecotoxicology',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
            "notes": 'Not currently offered',
          },
          {
            "subject": 'ENVR',
            "catalog": '540',
            "title": 'Ecology of Species Invasions',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
          },
          {
            "subject": 'PLNT',
            "catalog": '460',
            "title": 'Plant Ecology',
            "credits": 3.0,
            "choose_from_group": 'Area 1',
            "notes": 'Not currently offered',
          },
        ],
      },
      {
        "block_key": 'environment_interfaculty_basc_areas',
        "title": 'Areas (30 credits from at least three of five areas)',
        "block_type": 'pool_group',
        "credits_needed": 30,
        "notes": '30 credits from at least three of the following Areas. At least 6 credits must be at the 400 level or higher, selected either from these lists or in consultation with the Program Adviser.',
        "sort_order": 4,
      },
      {
        "block_key": 'environment_interfaculty_basc_area2',
        "title": 'Area 2: Biodiversity and Conservation',
        "block_type": 'group',
        "group_name": 'Area 2',
        "sort_order": 5,
        "courses": [
          {
            "subject": 'BIOL',
            "catalog": '305',
            "title": 'Animal Diversity',
            "credits": 3.0,
            "choose_from_group": 'Area 2',
          },
          {
            "subject": 'BIOL',
            "catalog": '310',
            "title": 'Biodiversity and Ecosystems',
            "credits": 3.0,
            "choose_from_group": 'Area 2',
          },
          {
            "subject": 'BIOL',
            "catalog": '343',
            "title": 'Biodiversity in the Caribbean',
            "credits": 3.0,
            "choose_from_group": 'Area 2',
          },
          {
            "subject": 'BIOL',
            "catalog": '427',
            "title": 'Herpetology',
            "credits": 3.0,
            "choose_from_group": 'Area 2',
            "notes": 'Not currently offered',
          },
          {
            "subject": 'BIOL',
            "catalog": '465',
            "title": 'Conservation Biology',
            "credits": 3.0,
            "choose_from_group": 'Area 2',
          },
          {
            "subject": 'MICR',
            "catalog": '331',
            "title": 'Microbial Ecology',
            "credits": 3.0,
            "choose_from_group": 'Area 2',
          },
          {
            "subject": 'PLNT',
            "catalog": '358',
            "title": 'Flowering Plant Diversity',
            "credits": 3.0,
            "choose_from_group": 'Area 2',
          },
          {
            "subject": 'WILD',
            "catalog": '307',
            "title": 'Natural History of Vertebrates',
            "credits": 3.0,
            "choose_from_group": 'Area 2',
          },
          {
            "subject": 'WILD',
            "catalog": '350',
            "title": 'Mammalogy',
            "credits": 3.0,
            "choose_from_group": 'Area 2',
          },
          {
            "subject": 'WILD',
            "catalog": '420',
            "title": 'Ornithology',
            "credits": 3.0,
            "choose_from_group": 'Area 2',
          },
        ],
      },
      {
        "block_key": 'environment_interfaculty_basc_area3',
        "title": 'Area 3: Field Studies in Ecology and Conservation',
        "block_type": 'group',
        "group_name": 'Area 3',
        "sort_order": 6,
        "courses": [
          {
            "subject": 'BIOL',
            "catalog": '240',
            "title": 'Monteregian Flora',
            "credits": 3.0,
            "choose_from_group": 'Area 3',
          },
          {
            "subject": 'BIOL',
            "catalog": '331',
            "title": 'Ecology/Behaviour Field Course',
            "credits": 3.0,
            "choose_from_group": 'Area 3',
          },
          {
            "subject": 'BIOL',
            "catalog": '334D1',
            "title": 'Applied Tropical Ecology',
            "credits": 1.5,
            "choose_from_group": 'Area 3',
            "notes": 'Field component at Bellairs Research Institute in Barbados, early May. Requires application.',
          },
          {
            "subject": 'BIOL',
            "catalog": '334D2',
            "title": 'Applied Tropical Ecology',
            "credits": 1.5,
            "choose_from_group": 'Area 3',
          },
          {
            "subject": 'BIOL',
            "catalog": '335',
            "title": 'Marine Mammals',
            "credits": 3.0,
            "choose_from_group": 'Area 3',
            "notes": 'Taught at Huntsman Marine Science Centre, St. Andrews, N.B., two weeks in August',
          },
          {
            "subject": 'BIOL',
            "catalog": '553',
            "title": 'Neotropical Environments',
            "credits": 3.0,
            "choose_from_group": 'Area 3',
          },
          {
            "subject": 'GEOG',
            "catalog": '495',
            "title": 'Field Studies - Physical Geography',
            "credits": 3.0,
            "choose_from_group": 'Area 3',
            "notes": 'May Summer session',
          },
          {
            "subject": 'WILD',
            "catalog": '475',
            "title": 'Desert Ecology',
            "credits": 3.0,
            "choose_from_group": 'Area 3',
            "notes": 'Not currently offered (page truncated)',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'environment_honours_basc',
    "name": 'Environment Honours (B.A. & Sc.) (60 credits)',
    "program_type": 'honours',
    "faculty": 'Faculty of Arts & Science',
    "total_credits": 60,
    "description": 'The B.A. & Sc. Honours in Environment extends the 54-credit Interfaculty Program in Environment with a 6-credit supervised research project. Students work closely with a faculty supervisor on an original research question related to environmental studies. Minimum program GPA of 3.3 required at graduation. Students must also complete an approved minor concentration.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts-science/programs/environment/',
    "blocks": [
      {
        "block_key": 'env_hon_research',
        "title": 'Additional Honours Research Requirement',
        "block_type": 'required',
        "credits_needed": 6,
        "constraint_notes": 'In addition to all 54 credits of the Environment Interfaculty Program, Honours students must complete 6 credits of supervised honours research.',
        "notes": 'In addition to all 54 credits of the Environment Interfaculty Program, Honours students must complete 6 credits of supervised honours research.',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'ENVR',
            "catalog": '490',
            "title": 'Honours Research in Environment',
            "credits": 6.0,
            "is_required": True,
          },
        ],
      },
      {
        "block_key": 'env_hon_note',
        "title": 'All Environment Interfaculty Requirements',
        "block_type": 'choose_credits',
        "credits_needed": 54,
        "constraint_notes": 'All required and complementary courses from the Environment Interfaculty Program (54 credits) apply. See the Environment Interfaculty Program (program_key: environment_interfaculty_basc) for full course lists.',
        "notes": 'All required and complementary courses from the Environment Interfaculty Program (54 credits) apply. See the Environment Interfaculty Program (program_key: environment_interfaculty_basc) for full course lists.',
        "sort_order": 2,
      },
    ],
  },
]


# ══════════════════════════════════════════════════════════════════════════
#  DATABASE SEED FUNCTION
# ══════════════════════════════════════════════════════════════════════════

def seed_degree_requirements(supabase):
    """
    Insert all B.A. & Sc. degree requirements into Supabase.
    Safe to re-run: uses upsert on program_key, then deletes+reinserts blocks.
    Courses are batch-inserted per block (one call per block) to avoid timeouts.
    """
    inserted_programs = 0
    inserted_blocks   = 0
    inserted_courses  = 0

    for prog in ARTS_SCIENCE_PROGRAMS:
        prog_data = {
            "program_key":   prog["program_key"],
            "name":          prog["name"],
            "faculty":       prog.get("faculty", "Faculty of Arts & Science"),
            "program_type":  prog["program_type"],
            "total_credits": prog.get("total_credits") or 0,
            "description":   prog.get("description"),
            "ecalendar_url": prog.get("ecalendar_url"),
        }
        result = supabase.table("degree_programs").upsert(
            prog_data, on_conflict="program_key"
        ).execute()
        prog_id = result.data[0]["id"]
        inserted_programs += 1

        supabase.table("requirement_blocks").delete().eq("program_id", prog_id).execute()

        for i, block in enumerate(prog.get("blocks", [])):
            constraint_notes = block.get("constraint_notes") or block.get("notes") or ""
            block_data = {
                "program_id":       prog_id,
                "block_key":        block.get("block_key", f"block_{i}"),
                "title":            block.get("title", ""),
                "block_type":       block.get("block_type", "choose_credits"),
                "group_name":       block.get("group_name"),
                "courses_needed":   block.get("courses_needed"),
                "constraint_notes": constraint_notes,
                "credits_needed":   block.get("credits_needed"),
                "min_level":        block.get("min_level"),
                "max_credits_200":  block.get("max_credits_200"),
                "min_credits_400":  block.get("min_credits_400"),
                "notes":            block.get("notes", ""),
                "sort_order":       block.get("sort_order", i),
            }
            block_result = supabase.table("requirement_blocks").insert(block_data).execute()
            block_id = block_result.data[0]["id"]
            inserted_blocks += 1

            courses_to_insert = []
            for j, course in enumerate(block.get("courses", [])):
                is_required = course.get("is_required", False)
                if block.get("block_type") == "required":
                    is_required = True
                courses_to_insert.append({
                    "block_id":              block_id,
                    "subject":               course.get("subject", ""),
                    "catalog":               course.get("catalog"),
                    "title":                 course.get("title", ""),
                    "credits":               course.get("credits", 3),
                    "is_required":           is_required,
                    "choose_from_group":     course.get("choose_from_group"),
                    "choose_n_credits":      course.get("choose_n_credits"),
                    "notes":                 course.get("notes"),
                    "recommended":           course.get("recommended", False),
                    "recommendation_reason": course.get("recommendation_reason"),
                    "sort_order":            j,
                })

            if courses_to_insert:
                supabase.table("requirement_courses").insert(courses_to_insert).execute()
                inserted_courses += len(courses_to_insert)

    return {
        "programs": inserted_programs,
        "blocks":   inserted_blocks,
        "courses":  inserted_courses,
    }


if __name__ == "__main__":
    import os, sys
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
    from api.utils.supabase_client import get_supabase
    supabase = get_supabase()
    stats = seed_degree_requirements(supabase)
    print(f"Seeded: {stats['programs']} programs, {stats['blocks']} blocks, {stats['courses']} courses")
