"""
McGill Faculty of Arts – Social Sciences: Cognitive Science, Anthropology, Economics, Political Science, Psychology, Sociology
Sub-module of arts_degree_requirements.py
"""

ARTS_SOCIAL_SCIENCES = [
  {
    "program_key": 'cognitive_science_minor',
    "name": 'Cognitive Science – Minor (B.Sc.)',
    "program_type": 'minor',
    "faculty": 'Faculty of Science',
    "total_credits": 24,
    "description": 'The Minor in Cognitive Science explores the interdisciplinary study of cognition, including the principles of intelligence, the mind and learning.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/cognitive-science/cognitive-science-minor-bsc/',
    "blocks": [
      {
        "block_key": 'cognitive_science_minor_required',
        "title": 'Required Course (3 credits)',
        "block_type": 'required',
        "credits_needed": 3,
        "sort_order": 1,
        "courses": [
          {
            "subject": 'PSYC',
            "catalog": '433',
            "title": 'Cognitive Science',
            "credits": 3.0,
            "is_required": True,
          },
        ],
      },
      {
        "block_key": 'cognitive_science_minor_complementary',
        "title": 'Complementary Courses (21 credits)',
        "block_type": 'pool_group',
        "credits_needed": 21,
        "notes": 'Students must take a minimum of 6 credits at the 400 to 500 level. Students may not take any courses from their home department(s). Students complete a minimum of 9 credits each in two areas.',
        "sort_order": 2,
      },
      {
        "block_key": 'cognitive_science_minor_cs_math',
        "title": 'Computer Science and Mathematics',
        "block_type": 'group',
        "group_name": 'Computer Science and Mathematics',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'COMP',
            "catalog": '206',
            "title": 'Introduction to Software Systems',
            "credits": 3.0,
            "choose_from_group": 'Computer Science and Mathematics',
          },
          {
            "subject": 'COMP',
            "catalog": '230',
            "title": 'Logic and Computability',
            "credits": 3.0,
            "choose_from_group": 'Computer Science and Mathematics',
          },
          {
            "subject": 'COMP',
            "catalog": '250',
            "title": 'Introduction to Computer Science',
            "credits": 3.0,
            "choose_from_group": 'Computer Science and Mathematics',
          },
          {
            "subject": 'COMP',
            "catalog": '251',
            "title": 'Algorithms and Data Structures',
            "credits": 3.0,
            "choose_from_group": 'Computer Science and Mathematics',
          },
          {
            "subject": 'COMP',
            "catalog": '302',
            "title": 'Programming Languages and Paradigms',
            "credits": 3.0,
            "choose_from_group": 'Computer Science and Mathematics',
          },
          {
            "subject": 'COMP',
            "catalog": '330',
            "title": 'Theory of Computation',
            "credits": 3.0,
            "choose_from_group": 'Computer Science and Mathematics',
          },
          {
            "subject": 'COMP',
            "catalog": '527',
            "title": 'Logic and Computation',
            "credits": 3.0,
            "choose_from_group": 'Computer Science and Mathematics',
          },
          {
            "subject": 'MATH',
            "catalog": '240',
            "title": 'Discrete Structures',
            "credits": 3.0,
            "choose_from_group": 'Computer Science and Mathematics',
          },
          {
            "subject": 'MATH',
            "catalog": '318',
            "title": 'Mathematical Logic',
            "credits": 3.0,
            "choose_from_group": 'Computer Science and Mathematics',
          },
        ],
      },
      {
        "block_key": 'cognitive_science_minor_linguistics',
        "title": 'Linguistics',
        "block_type": 'group',
        "group_name": 'Linguistics',
        "notes": 'Any course at the 300, 400 or 500 level from the department of Linguistics, or the listed courses below.',
        "sort_order": 4,
        "courses": [
          {
            "subject": 'LING',
            "catalog": '201',
            "title": 'Introduction to Linguistics',
            "credits": 3.0,
            "choose_from_group": 'Linguistics',
          },
          {
            "subject": 'LING',
            "catalog": '210',
            "title": 'Introduction to Speech Science',
            "credits": 3.0,
            "choose_from_group": 'Linguistics',
          },
          {
            "subject": 'LING',
            "catalog": '260',
            "title": 'Meaning in Language',
            "credits": 3.0,
            "choose_from_group": 'Linguistics',
          },
        ],
      },
      {
        "block_key": 'cognitive_science_minor_philosophy',
        "title": 'Philosophy',
        "block_type": 'group',
        "group_name": 'Philosophy',
        "sort_order": 5,
        "courses": [
          {
            "subject": 'PHIL',
            "catalog": '203',
            "title": 'Introduction to Artificial Intelligence Ethics',
            "credits": 3.0,
            "choose_from_group": 'Philosophy',
          },
          {
            "subject": 'PHIL',
            "catalog": '210',
            "title": 'Introduction to Deductive Logic 1',
            "credits": 3.0,
            "choose_from_group": 'Philosophy',
          },
          {
            "subject": 'PHIL',
            "catalog": '221',
            "title": 'Introduction to History and Philosophy of Science 2',
            "credits": 3.0,
            "choose_from_group": 'Philosophy',
          },
          {
            "subject": 'PHIL',
            "catalog": '306',
            "title": 'Philosophy of Mind',
            "credits": 3.0,
            "choose_from_group": 'Philosophy',
          },
          {
            "subject": 'PHIL',
            "catalog": '310',
            "title": 'Intermediate Logic',
            "credits": 3.0,
            "choose_from_group": 'Philosophy',
          },
          {
            "subject": 'PHIL',
            "catalog": '311',
            "title": 'Philosophy of Mathematics',
            "credits": 3.0,
            "choose_from_group": 'Philosophy',
          },
          {
            "subject": 'PHIL',
            "catalog": '341',
            "title": 'Philosophy of Science 1',
            "credits": 3.0,
            "choose_from_group": 'Philosophy',
          },
          {
            "subject": 'PHIL',
            "catalog": '411',
            "title": 'Topics in Philosophy of Logic and Mathematics',
            "credits": 3.0,
            "choose_from_group": 'Philosophy',
          },
          {
            "subject": 'PHIL',
            "catalog": '415',
            "title": 'Philosophy of Language',
            "credits": 3.0,
            "choose_from_group": 'Philosophy',
          },
          {
            "subject": 'PHIL',
            "catalog": '441',
            "title": 'Philosophy of Science 2',
            "credits": 3.0,
            "choose_from_group": 'Philosophy',
          },
          {
            "subject": 'PHIL',
            "catalog": '474',
            "title": 'Phenomenology',
            "credits": 3.0,
            "choose_from_group": 'Philosophy',
          },
        ],
      },
      {
        "block_key": 'cognitive_science_minor_psychology',
        "title": 'Psychology',
        "block_type": 'group',
        "group_name": 'Psychology',
        "sort_order": 6,
        "courses": [
          {
            "subject": 'PSYC',
            "catalog": '211',
            "title": 'Introductory Behavioural Neuroscience',
            "credits": 3.0,
            "choose_from_group": 'Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '213',
            "title": 'Cognition',
            "credits": 3.0,
            "choose_from_group": 'Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '304',
            "title": 'Child Development',
            "credits": 3.0,
            "choose_from_group": 'Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '311',
            "title": 'Human Cognition and the Brain',
            "credits": 3.0,
            "choose_from_group": 'Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '315',
            "title": 'Computational Psychology',
            "credits": 3.0,
            "choose_from_group": 'Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '340',
            "title": 'Psychology of Language',
            "credits": 3.0,
            "choose_from_group": 'Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '341',
            "title": 'The Psychology of Bilingualism',
            "credits": 3.0,
            "choose_from_group": 'Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '403',
            "title": 'Modern Psychology in Historical Perspective',
            "credits": 3.0,
            "choose_from_group": 'Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '406',
            "title": 'Psychological Tests',
            "credits": 3.0,
            "choose_from_group": 'Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '410',
            "title": 'Special Topics in Neuropsychology',
            "credits": 3.0,
            "choose_from_group": 'Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '413',
            "title": 'Cognitive Development',
            "credits": 3.0,
            "choose_from_group": 'Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '427',
            "title": 'Sensorimotor Neuroscience',
            "credits": 3.0,
            "choose_from_group": 'Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '443',
            "title": 'Affective Neuroscience',
            "credits": 3.0,
            "choose_from_group": 'Psychology',
          },
          {
            "subject": 'PSYC',
            "catalog": '538',
            "title": 'Categorization, Communication and Consciousness',
            "credits": 3.0,
            "choose_from_group": 'Psychology',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'anthropology_major',
    "name": 'Anthropology – Major Concentration',
    "program_type": 'major',
    "faculty": 'Faculty of Arts',
    "total_credits": 36,
    "description": 'Emphasises the similarity and diversity of human behaviour; understanding of social and cultural systems; and the processes of socio-cultural change from human origins to the present.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/anthropology/anthropology-major-concentration-ba/',
    "blocks": [
      {
        "block_key": 'anthropology_major_200level',
        "title": '200 Level (6 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 6,
        "notes": '6 credits selected from 200-level courses in Anthropology (ANTH).',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'ANTH',
            "catalog": '200',
            "title": 'Any 200-level Anthropology course',
            "notes": 'Placeholder for any 200-level ANTH course',
          },
        ],
      },
      {
        "block_key": 'anthropology_major_core_350',
        "title": 'Core (350 Level) (6 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 6,
        "notes": 'Restricted to students in any Anthropology program with U2 standing or above.',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'ANTH',
            "catalog": '352',
            "title": 'History of Anthropological Theory',
            "credits": 3.0,
          },
          {
            "subject": 'ANTH',
            "catalog": '355',
            "title": 'Theories of Culture and Society',
            "credits": 3.0,
          },
          {
            "subject": 'ANTH',
            "catalog": '357',
            "title": 'Archaeological Methods',
            "credits": 3.0,
          },
          {
            "subject": 'ANTH',
            "catalog": '358',
            "title": 'The Process of Anthropological Research',
            "credits": 3.0,
          },
          {
            "subject": 'ANTH',
            "catalog": '359',
            "title": 'History of Archaeological Theory',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'anthropology_major_400level',
        "title": '400 Level (6 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 6,
        "courses_needed": 2,
        "notes": 'Two 400-level Anthropology (ANTH) courses.',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'ANTH',
            "catalog": '400',
            "title": 'Any 400-level Anthropology course',
            "credits": 3.0,
            "notes": 'Placeholder for 400-level ANTH courses',
          },
        ],
      },
      {
        "block_key": 'anthropology_major_additional_undergrad',
        "title": 'Additional Undergraduate Courses (18 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 18,
        "notes": '18 credits of additional undergraduate-level Anthropology courses of which no more than 6 credits may be at the 200 level.',
        "sort_order": 4,
        "courses": [
          {
            "subject": 'ANTH',
            "catalog": '100',
            "title": 'Any undergraduate-level Anthropology course',
            "notes": 'Placeholder for undergraduate ANTH courses; max 6 credits at 200-level',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'anthropology_minor',
    "name": 'Anthropology – Minor Concentration',
    "program_type": 'minor',
    "faculty": 'Faculty of Arts',
    "total_credits": 18,
    "description": '18 credits in Anthropology. May focus on one sub-field or explore all. Can be expanded into the Major.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/anthropology/anthropology-minor-concentration-ba/',
    "blocks": [
      {
        "block_key": 'anthropology_minor_200level',
        "title": '200-level Anthropology Courses',
        "block_type": 'choose_credits',
        "credits_needed": 6,
        "notes": 'Choose between 6-9 credits from 200-level Anthropology courses.',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'ANTH',
            "catalog": '200',
            "title": 'Any 200-level Anthropology course',
          },
        ],
      },
      {
        "block_key": 'anthropology_minor_300plus',
        "title": '300+, 400, or 500-level Anthropology Courses',
        "block_type": 'choose_credits',
        "credits_needed": 9,
        "notes": 'Choose between 9-12 credits from 300-, 400-, or 500-level Anthropology courses. Only 3 credits maximum from 400 or 500-level courses. Only 1 Special Topic course may be taken.',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'ANTH',
            "catalog": '300',
            "title": 'Any 300-level Anthropology course',
          },
          {
            "subject": 'ANTH',
            "catalog": '400',
            "title": 'Any 400-level Anthropology course',
            "notes": 'Maximum 3 credits from 400 or 500-level courses combined.',
          },
          {
            "subject": 'ANTH',
            "catalog": '500',
            "title": 'Any 500-level Anthropology course',
            "notes": 'Maximum 3 credits from 400 or 500-level courses combined.',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'economics_major',
    "name": 'Economics – Major Concentration',
    "program_type": 'major',
    "faculty": 'Faculty of Arts',
    "total_credits": 36,
    "description": 'A planned sequence of courses designed to permit the student a degree of specialization in economics. Students entering U1 proceed directly to ECON 230D1/D2 (not ECON 208/209).',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/economics/economics-major-concentration-ba/',
    "blocks": [
      {
        "block_key": 'economics_major_required',
        "title": 'Required Courses (18 credits)',
        "block_type": 'required',
        "credits_needed": 18,
        "notes": "All students must take 6 credits of approved statistics courses. Students should refer to the Department's document 'Rules on Stats Courses for Economics Students' at http://www.mcgill.ca/economics/undergraduates/courses/",
        "sort_order": 1,
        "courses": [
          {
            "subject": 'ECON',
            "catalog": '227D1',
            "title": 'Economic Statistics.',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Take D1 or D2, not both. Distributions, averages, dispersions, sampling, testing, estimation, correlation, regression, index numbers, trends and seasonals.',
          },
          {
            "subject": 'ECON',
            "catalog": '227D2',
            "title": 'Economic Statistics.',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Take D1 or D2, not both. Same course as ECON 227D1.',
          },
          {
            "subject": 'ECON',
            "catalog": '230D1',
            "title": 'Microeconomic Theory.',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Take D1 or D2, not both. The introductory course for Economics Major students in microeconomic theory. In depth and critical presentation of the theory of consumer behaviour, theory of production and cost curves, theory of the firm, theory of distribution, welfare economics and the theory of general equilibrium.',
          },
          {
            "subject": 'ECON',
            "catalog": '230D2',
            "title": 'Microeconomic Theory.',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Take D1 or D2, not both. Same course as ECON 230D1.',
          },
          {
            "subject": 'ECON',
            "catalog": '332',
            "title": 'Macroeconomic Theory: Majors 1.',
            "credits": 3.0,
            "is_required": True,
            "notes": 'A review of basic economic concepts and tools with an in depth and critical presentation of the fundamental areas of macroeconomic theory. Topics include: the measurement of economic aggregates, economic growth, and the consumption-savings decision and other basic elements of a business cycle.',
          },
          {
            "subject": 'ECON',
            "catalog": '333',
            "title": 'Macroeconomic Theory - Majors 2.',
            "credits": 3.0,
            "is_required": True,
            "notes": 'A review of basic economic concepts and tools with an in depth and critical presentation of the fundamental areas of macroeconomic theory. Topics include: money and banking and business cycles, stabilization policy, and international finance.',
          },
        ],
      },
      {
        "block_key": 'economics_major_complementary',
        "title": 'Complementary Courses (18 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 18,
        "notes": "18 credits in Economics selected from other 200- (with numbers above 209), 300-, 400- and 500-level courses. At least 6 of these credits must be in 400- or 500-level courses. No more than 6 credits may be at the 200 level. Consult the Department's website for available course list: www.mcgill.ca/economics/undergraduates/majorminor",
        "sort_order": 2,
        "courses": [
          {
            "subject": 'ECON',
            "catalog": '2XX',
            "title": 'Any 200-level Economics course (excluding ECON 200-209)',
            "credits": 3.0,
            "notes": 'Maximum 6 credits total at 200 level. Course numbers must be above 209.',
          },
          {
            "subject": 'ECON',
            "catalog": '3XX',
            "title": 'Any 300-level Economics course',
            "credits": 3.0,
          },
          {
            "subject": 'ECON',
            "catalog": '4XX',
            "title": 'Any 400-level Economics course',
            "credits": 3.0,
            "notes": 'Minimum 6 credits required at 400 or 500 level.',
          },
          {
            "subject": 'ECON',
            "catalog": '5XX',
            "title": 'Any 500-level Economics course',
            "credits": 3.0,
            "notes": 'Minimum 6 credits required at 400 or 500 level.',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'economics_minor',
    "name": 'Economics – Minor Concentration',
    "program_type": 'minor',
    "faculty": 'Faculty of Arts',
    "total_credits": 18,
    "description": 'The Minor Concentration in Economics provides a moderate level of specialization in Economics for students who usually are pursuing Major Concentrations or Honours Programs in other fields of study. It does, however, provide an option to switch to or add a Major Concentration in Economics. There is a special Minor for Management students.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/economics/economics-minor-concentration-ba/',
    "blocks": [
      {
        "block_key": 'economics_minor_complementary',
        "title": 'Complementary Courses (18 credits)',
        "block_type": 'multi_group',
        "credits_needed": 18,
        "notes": '18 credits total: 6 credits from Group A and 12 credits from Group B.',
        "sort_order": 1,
      },
      {
        "block_key": 'economics_minor_group_a',
        "title": 'Group A',
        "block_type": 'group',
        "group_name": 'Group A',
        "credits_needed": 6,
        "notes": 'Choose 6 credits from Group A. See Program Notes for mutual exclusion rules regarding ECON 208, 230D1/D2, and 250D1/D2.',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'ECON',
            "catalog": '208',
            "title": 'Microeconomic Analysis and Applications',
            "credits": 3.0,
            "choose_from_group": 'Group A',
            "notes": 'A university-level introduction to demand and supply, consumer behaviour, production theory, market structures and income distribution theory.',
          },
          {
            "subject": 'ECON',
            "catalog": '209',
            "title": 'Macroeconomic Analysis and Applications',
            "credits": 3.0,
            "choose_from_group": 'Group A',
            "notes": 'A university-level introduction to national income determination, money and banking, inflation, unemployment and economic policy.',
          },
          {
            "subject": 'ECON',
            "catalog": '230D1',
            "title": 'Microeconomic Theory',
            "credits": 3.0,
            "choose_from_group": 'Group A',
            "notes": 'The introductory course for Economics Major students in microeconomic theory. In depth and critical presentation of the theory of consumer behaviour, theory of production and cost curves, theory of the firm, theory of distribution, welfare economics and the theory of general equilibrium.',
          },
          {
            "subject": 'ECON',
            "catalog": '230D2',
            "title": 'Microeconomic Theory',
            "credits": 3.0,
            "choose_from_group": 'Group A',
            "notes": 'See ECON 230D1 for course description.',
          },
        ],
      },
      {
        "block_key": 'economics_minor_group_b',
        "title": 'Group B',
        "block_type": 'group',
        "group_name": 'Group B',
        "credits_needed": 12,
        "notes": 'Choose 12 credits from Group B. Group B consists of Economics courses with course numbers above ECON 208 (excluding ECON 295), with at least 6 credits at the 300, 400 or 500 level. See Program Notes for mutual exclusion rules regarding ECON 209, ECON 332/333, and ECON 353/354.',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'ECON',
            "catalog": 'level_elective_300_400_500',
            "title": 'Any ECON course at 300, 400, or 500 level',
            "credits": 3.0,
            "choose_from_group": 'Group B',
            "notes": 'At least 6 of the 12 Group B credits must be from courses at the 300, 400, or 500 level.',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'political_science_major',
    "name": 'Political Science – Major Concentration',
    "program_type": 'major',
    "faculty": 'Faculty of Arts',
    "total_credits": 36,
    "description": 'A 36-credit program covering four fields: Comparative Politics, International Relations, Canadian Politics, and Political Theory. Methods courses (POLI 210/311/312/313) may count toward any field. Max 18 credits in any single field (21 for Comparative Politics). At least one 200-level course in a field before taking 300/400-level courses in that field.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/political-science/political-science-major-concentration-ba/',
    "blocks": [
      {
        "block_key": 'political_science_major_complementary',
        "title": 'Complementary Courses (36 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 36,
        "notes": '36 credits selected from four fields: Canadian Politics, Comparative Politics, International Relations, and Political Theory. Constraints: (1) 12 credits at 200-level (max 3 per field group); (2) 24 credits at 300+ level; (3) 3 credits at 400-level McGill required; (4) max 18 credits per field (21 for Comparative Politics); (5) must take 200-level course in field before 300+level in that field; (6) max 12 transfer credits; (7) POLI 599 cannot fulfill 400-level requirement.',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'POLI',
            "catalog": '221',
            "title": 'Government of Canada',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '222',
            "title": 'Political Process and Behaviour in Canada',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '226',
            "title": 'La vie politique québécoise',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '317',
            "title": 'The Politics of Race in Canada',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '318',
            "title": 'Comparative Local Government',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
            "notes": 'Course also appears in Comparative Politics field',
          },
          {
            "subject": 'POLI',
            "catalog": '320',
            "title": 'Issues in Canadian Democracy',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '321',
            "title": 'Issues: Canadian Public Policy',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '336',
            "title": 'Le Québec et le Canada',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '342',
            "title": 'Canadian Foreign Policy',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '348',
            "title": 'Gender and Canadian Politics',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '371',
            "title": 'Challenge of Canadian Federalism',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '372',
            "title": 'Indigenous Peoples and the Canadian State',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '379',
            "title": 'Topics in Canadian Politics',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '410',
            "title": 'Canadian Political Parties',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '412',
            "title": 'Canadian Voting/Public Opinion',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '417',
            "title": 'Health Care in Canada',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '424',
            "title": 'Media and Politics',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '426',
            "title": 'Partis politiques et comportements électoraux au Québec',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '427',
            "title": 'Selected Topics: Canadian Politics',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '436',
            "title": 'Aboriginal Rights in the Canadian Constitution',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '212',
            "title": 'Introduction to Comparative Politics – Europe/North America',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '227',
            "title": 'Introduction to Comparative Politics - Global South',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '316',
            "title": 'Black Lives Matter and American Democracy',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '318',
            "title": 'Comparative Local Government',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
            "notes": 'Course also appears in Canadian Politics field',
          },
          {
            "subject": 'POLI',
            "catalog": '319',
            "title": 'Politics of Latin America',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '322',
            "title": 'Political Change in South Asia',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '324',
            "title": 'Comparative Politics of Africa',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '325',
            "title": 'U.S. Politics',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '328',
            "title": 'Comparing European Democracies',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '329',
            "title": 'Russian Politics',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '330',
            "title": 'Law and Courts in Europe',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '331',
            "title": 'Politics in East Central Europe',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '338',
            "title": 'Topics in Comparative Politics 1',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '339',
            "title": 'Topics in Comparative Politics 2',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '340',
            "title": 'Comparative Politics of the Middle East',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '357',
            "title": 'Politics: Contemporary Europe',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '361',
            "title": 'Political Participation in Comparative Perspective',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '369',
            "title": 'Politics of Southeast Asia',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '380',
            "title": 'Contemporary Chinese Politics',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '381',
            "title": 'Politics in Japan and South Korea',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '420',
            "title": 'Memory, Place, and Power',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '421',
            "title": 'The Politics of Misinformation',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
            "notes": 'Course description truncated in source',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'political_science_minor',
    "name": 'Political Science – Minor Concentration',
    "program_type": 'minor',
    "faculty": 'Faculty of Arts',
    "total_credits": 18,
    "description": 'An 18-credit program in four fields: Comparative Politics, International Relations, Canadian Politics, and Political Theory.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/political-science/political-science-minor-concentration-ba/',
    "blocks": [
      {
        "block_key": 'political_science_minor_200level',
        "title": '200-Level POLI Courses (6-9 credits)',
        "block_type": 'multi_group',
        "credits_needed": 6,
        "notes": '6 or 9 POLI credits at the 200 level. Each course must be from a different group (Canadian Politics, International Relations, Comparative Politics, Political Theory, Methods). Students must choose courses from at least one and up to five different groups, with a total of 6-9 credits.',
        "sort_order": 1,
      },
      {
        "block_key": 'political_science_minor_canadian_politics_200',
        "title": 'Canadian Politics (200-level)',
        "block_type": 'group',
        "group_name": 'Canadian Politics',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'POLI',
            "catalog": '221',
            "title": 'Government of Canada',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '222',
            "title": 'Political Process and Behaviour in Canada',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '226',
            "title": 'La vie politique québécoise',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
        ],
      },
      {
        "block_key": 'political_science_minor_comparative_politics_200',
        "title": 'Comparative Politics (200-level)',
        "block_type": 'group',
        "group_name": 'Comparative Politics',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'POLI',
            "catalog": '212',
            "title": 'Introduction to Comparative Politics – Europe/North America',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '227',
            "title": 'Introduction to Comparative Politics - Global South',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
        ],
      },
      {
        "block_key": 'political_science_minor_international_relations_200',
        "title": 'International Relations (200-level)',
        "block_type": 'group',
        "group_name": 'International Relations',
        "notes": 'Course list not provided in extracted text.',
        "sort_order": 4,
      },
      {
        "block_key": 'political_science_minor_political_theory_200',
        "title": 'Political Theory (200-level)',
        "block_type": 'group',
        "group_name": 'Political Theory',
        "notes": 'Course list not provided in extracted text.',
        "sort_order": 5,
      },
      {
        "block_key": 'political_science_minor_methods_200',
        "title": 'Methods (200-level)',
        "block_type": 'group',
        "group_name": 'Methods',
        "notes": 'Course list not provided in extracted text.',
        "sort_order": 6,
      },
      {
        "block_key": 'political_science_minor_300_400level',
        "title": '300- and 400-Level POLI Courses (9-12 credits)',
        "block_type": 'pool_group',
        "credits_needed": 9,
        "notes": 'The remaining 9 or 12 credits must come from POLI courses at the 300 or 400 level in any group(s). Prerequisite: students must have taken a 200-level POLI course in the same field to take a 300- or 400-level course in that field. No more than 6 POLI transfer credits can be used toward program requirements. POLI 490 (Independent Reading and Research) and POLI 499 (Honours Essay) are not open to students in the Minor Concentration.',
        "sort_order": 7,
      },
      {
        "block_key": 'political_science_minor_canadian_politics_300_400',
        "title": 'Canadian Politics (300- and 400-level)',
        "block_type": 'group',
        "group_name": 'Canadian Politics',
        "sort_order": 8,
        "courses": [
          {
            "subject": 'POLI',
            "catalog": '318',
            "title": 'Comparative Local Government',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
            "notes": 'Listed under Canadian Politics but also listed under Comparative Politics in the catalogue.',
          },
          {
            "subject": 'POLI',
            "catalog": '320',
            "title": 'Issues in Canadian Democracy',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '321',
            "title": 'Issues: Canadian Public Policy',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '336',
            "title": 'Le Québec et le Canada',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '342',
            "title": 'Canadian Foreign Policy',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '348',
            "title": 'Gender and Canadian Politics',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '371',
            "title": 'Challenge of Canadian Federalism',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '372',
            "title": 'Indigenous Peoples and the Canadian State',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '379',
            "title": 'Topics in Canadian Politics',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '410',
            "title": 'Canadian Political Parties',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '412',
            "title": 'Canadian Voting/Public Opinion',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '417',
            "title": 'Health Care in Canada',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '424',
            "title": 'Media and Politics',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
            "notes": 'Listed under Canadian Politics but also listed under Comparative Politics in the catalogue.',
          },
          {
            "subject": 'POLI',
            "catalog": '426',
            "title": 'Partis politiques et comportements électoraux au Québec',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '427',
            "title": 'Selected Topics: Canadian Politics',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '436',
            "title": 'Aboriginal Rights in the Canadian Constitution',
            "credits": 3.0,
            "choose_from_group": 'Canadian Politics',
          },
        ],
      },
      {
        "block_key": 'political_science_minor_comparative_politics_300_400',
        "title": 'Comparative Politics (300- and 400-level)',
        "block_type": 'group',
        "group_name": 'Comparative Politics',
        "sort_order": 9,
        "courses": [
          {
            "subject": 'POLI',
            "catalog": '316',
            "title": 'Black Lives Matter and American Democracy',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '318',
            "title": 'Comparative Local Government',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
            "notes": 'Listed under Comparative Politics but also listed under Canadian Politics in the catalogue.',
          },
          {
            "subject": 'POLI',
            "catalog": '319',
            "title": 'Politics of Latin America',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '322',
            "title": 'Political Change in South Asia',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '324',
            "title": 'Comparative Politics of Africa',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '325',
            "title": 'U.S. Politics',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '328',
            "title": 'Comparing European Democracies',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '329',
            "title": 'Russian Politics',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '330',
            "title": 'Law and Courts in Europe',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '331',
            "title": 'Politics in East Central Europe',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '338',
            "title": 'Topics in Comparative Politics 1',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '339',
            "title": 'Topics in Comparative Politics 2',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '340',
            "title": 'Comparative Politics of the Middle East',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '357',
            "title": 'Politics: Contemporary Europe',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '361',
            "title": 'Political Participation in Comparative Perspective',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '369',
            "title": 'Politics of Southeast Asia',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '380',
            "title": 'Contemporary Chinese Politics',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '381',
            "title": 'Politics in Japan and South Korea',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '420',
            "title": 'Memory, Place, and Power',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '421',
            "title": 'The Politics of Misinformation',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '422',
            "title": 'Advanced Topics in Comparative Politics 1',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '423',
            "title": 'Politics of Ethno-Nationalism',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
          {
            "subject": 'POLI',
            "catalog": '424',
            "title": 'Media and Politics',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
            "notes": 'Listed under Comparative Politics but also listed under Canadian Politics in the catalogue.',
          },
          {
            "subject": 'POLI',
            "catalog": '430',
            "title": 'Politics of Art',
            "credits": 3.0,
            "choose_from_group": 'Comparative Politics',
          },
        ],
      },
      {
        "block_key": 'political_science_minor_international_relations_300_400',
        "title": 'International Relations (300- and 400-level)',
        "block_type": 'group',
        "group_name": 'International Relations',
        "notes": 'Course list not provided in extracted text.',
        "sort_order": 10,
      },
      {
        "block_key": 'political_science_minor_political_theory_300_400',
        "title": 'Political Theory (300- and 400-level)',
        "block_type": 'group',
        "group_name": 'Political Theory',
        "notes": 'Course list not provided in extracted text.',
        "sort_order": 11,
      },
      {
        "block_key": 'political_science_minor_methods_300_400',
        "title": 'Methods (300- and 400-level)',
        "block_type": 'group',
        "group_name": 'Methods',
        "notes": 'Course list not provided in extracted text.',
        "sort_order": 12,
      },
    ],
  },
  {
    "program_key": 'psychology_major',
    "name": 'Psychology – Major Concentration',
    "program_type": 'major',
    "faculty": 'Faculty of Arts',
    "total_credits": 36,
    "description": 'Provides a basic overview of psychological science covering core areas and advanced specialized content. Note: PSYC 204 exemption possible for CEGEP students with statistics background.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/psychology/psychology-major-concentration-ba/',
    "blocks": [
      {
        "block_key": 'psychology_major_prerequisites_psyc',
        "title": 'Program Prerequisites – Psychology (0 or 3 credits)',
        "block_type": 'required',
        "credits_needed": 3,
        "notes": 'Required only if not completed equivalent in CEGEP. Introduction to Psychology in CEGEP is equivalent to PSYC 100.',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'PSYC',
            "catalog": '100',
            "title": 'Introduction to Psychology.',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Required only if General Psychology not completed in CEGEP.',
          },
        ],
      },
      {
        "block_key": 'psychology_major_prerequisites_biol',
        "title": 'Program Prerequisites – Biology (0 or 3 credits)',
        "block_type": 'choose_courses',
        "credits_needed": 3,
        "courses_needed": 1,
        "notes": 'Required only if Human Biology or General Biology not completed in CEGEP. Choose one of BIOL 111, 112, or 115.',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'BIOL',
            "catalog": '111',
            "title": 'Principles: Organismal Biology.',
            "credits": 3.0,
          },
          {
            "subject": 'BIOL',
            "catalog": '112',
            "title": 'Cell and Molecular Biology.',
            "credits": 3.0,
          },
          {
            "subject": 'BIOL',
            "catalog": '115',
            "title": 'Essential Biology.',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'psychology_major_required',
        "title": 'Required Courses (18 credits)',
        "block_type": 'required',
        "credits_needed": 18,
        "notes": 'PSYC 204 may be waived for eligible CEGEP students (stats background with min. 75%); if exempt, replace with 3 credits at 300-level or above in PSYC, ANTH, LING, or SOCI. PSYC 305 must be completed in U1 for students wishing to apply to the Honours program.',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'PSYC',
            "catalog": '204',
            "title": 'Introduction to Psychological Statistics.',
            "credits": 3.0,
            "is_required": True,
            "notes": 'CEGEP students may be exempt if they completed Quantitative Methods + Advanced Quantitative Methods or Statistics for Social Science, or Probability & Statistics / Statistics, with min. 75%. Exempt students replace this with 3 credits at 300+ level in PSYC, ANTH, LING, or SOCI.',
          },
          {
            "subject": 'PSYC',
            "catalog": '211',
            "title": 'Introductory Behavioural Neuroscience.',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'PSYC',
            "catalog": '212',
            "title": 'Perception.',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'PSYC',
            "catalog": '213',
            "title": 'Cognition.',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'PSYC',
            "catalog": '215',
            "title": 'Social Psychology.',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'PSYC',
            "catalog": '305',
            "title": 'Statistics for Experimental Design.',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Must be taken in U1 for Honours program eligibility.',
          },
        ],
      },
      {
        "block_key": 'psychology_major_complementary_list_a',
        "title": 'Complementary Courses – List A: Behavioural Neuroscience, Cognition and Quantitative Methods (3 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 3,
        "notes": 'Choose 3 credits from List A. Note: page was truncated; PSYC 319 and any courses after it may be incomplete. PSYC 312 appeared with no title or credits and was omitted.',
        "sort_order": 4,
        "courses": [
          {
            "subject": 'NSCI',
            "catalog": '201',
            "title": 'Introduction to Neuroscience 2.',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '301',
            "title": 'Animal Learning and Theory.',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '302',
            "title": 'Pain.',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '306',
            "title": 'Research Methods in Psychology.',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '310',
            "title": 'Intelligence.',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '311',
            "title": 'Human Cognition and the Brain.',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '315',
            "title": 'Computational Psychology.',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '317',
            "title": 'Genes and Behaviour.',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '318',
            "title": 'Behavioural Neuroscience 2.',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '319',
            "title": 'Computational Models - Cognition.',
            "credits": 3.0,
            "notes": 'Page truncated after this course; description and any additional List A courses after PSYC 319 are missing.',
          },
        ],
      },
      {
        "block_key": 'psychology_major_complementary_list_b',
        "title": 'Complementary Courses – List B: Social, Health and Developmental Psychology (3 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 3,
        "notes": 'Page was truncated before List B was shown. List B courses are not available from the extracted text. Advisor should verify the full list.',
        "sort_order": 5,
      },
      {
        "block_key": 'psychology_major_complementary_300level',
        "title": 'Complementary Courses – Psychology 300-level or above (6 credits)',
        "block_type": 'level_elective',
        "credits_needed": 6,
        "notes": '6 credits in Psychology (PSYC) at the 300 level or above. Specific eligible courses not enumerated; any PSYC 300+ course qualifies per catalogue.',
        "sort_order": 6,
      },
      {
        "block_key": 'psychology_major_complementary_400_500level',
        "title": 'Complementary Courses – Psychology 400 or 500-level (6 credits)',
        "block_type": 'level_elective',
        "credits_needed": 6,
        "notes": '6 credits in Psychology (PSYC) at the 400 or 500 level. Specific eligible courses not enumerated; any PSYC 400+ or 500+ course qualifies per catalogue.',
        "sort_order": 7,
      },
    ],
  },
  {
    "program_key": 'psychology_minor',
    "name": 'Psychology – Minor Concentration',
    "program_type": 'minor',
    "faculty": 'Faculty of Arts',
    "total_credits": 18,
    "description": "Psychology is the scientific study of the mind and behaviour. The B.A. Minor Concentration Psychology (18 credits) is intended to compliment the student's primary field of study by providing a focused introduction to specialized topics in psychology.",
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/psychology/psychology-minor-concentration-ba/',
    "blocks": [
      {
        "block_key": 'psychology_minor_200level_select',
        "title": 'Complementary Courses – 200-Level Selection (6 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 6,
        "notes": 'Select 6 credits from the following 200-level Psychology courses.',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'PSYC',
            "catalog": '204',
            "title": 'Introduction to Psychological Statistics.',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '211',
            "title": 'Introductory Behavioural Neuroscience.',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '212',
            "title": 'Perception.',
            "credits": 3.0,
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'PSYC',
            "catalog": '213',
            "title": 'Cognition.',
            "credits": 3.0,
          },
          {
            "subject": 'PSYC',
            "catalog": '215',
            "title": 'Social Psychology.',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'psychology_minor_300level',
        "title": 'Complementary Courses – 300-Level and Above (12 credits)',
        "block_type": 'level_elective',
        "credits_needed": 12,
        "notes": '12 credits in Psychology at the 300 level or above.',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'PSYC',
            "catalog": '300',
            "title": 'Any Psychology course at 300-level or above',
            "notes": 'Level elective placeholder; students select from available PSYC 300+ courses.',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'sociology_major',
    "name": 'Sociology – Major Concentration',
    "program_type": 'major',
    "faculty": 'Faculty of Arts',
    "total_credits": 36,
    "description": 'Gives students a comprehensive understanding of sociology. Required courses (SOCI 210, 211, 330, 350) must be taken at McGill.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/sociology/sociology-major-concentration-ba/',
    "blocks": [
      {
        "block_key": 'sociology_major_u1_required',
        "title": 'U1 Required Courses (6 credits)',
        "block_type": 'required',
        "credits_needed": 6,
        "sort_order": 1,
        "courses": [
          {
            "subject": 'SOCI',
            "catalog": '210',
            "title": 'Sociological Perspectives',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Must be taken at McGill.',
          },
          {
            "subject": 'SOCI',
            "catalog": '211',
            "title": 'Sociological Inquiry',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Must be taken at McGill.',
          },
        ],
      },
      {
        "block_key": 'sociology_major_u2_required',
        "title": 'U2 Required Courses (6 credits)',
        "block_type": 'required',
        "credits_needed": 6,
        "notes": 'Students exempted from SOCI 350 must replace it with another 300-level or higher sociology course.',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'SOCI',
            "catalog": '330',
            "title": 'Sociological Theory',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Must be taken at McGill.',
          },
          {
            "subject": 'SOCI',
            "catalog": '350',
            "title": 'Statistics in Social Research',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Must be taken at McGill. Students exempted from this course must replace it with another 300-level or higher sociology course.',
          },
        ],
      },
      {
        "block_key": 'sociology_major_complementary',
        "title": 'Complementary Courses (24 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 24,
        "notes": '24 credits of complementary sociology courses with the following constraints: (1) Minimum 3 credits at 400-level or higher; (2) Maximum 9 credits at 200-level; (3) No more than 6 credits combined from SOCI 341, 342, 343, 441, 442, 443 (current problems, independent study, and reading courses). Courses are organized into 4 substantive areas for guidance: Institutions/Deviance/Culture, Politics and Social Change, Social Stratification, and Work/Organizations/Economy.',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'SOCI',
            "catalog": '212',
            "title": 'International Migration',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '213',
            "title": 'Deviance',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '222',
            "title": 'Urban Sociology',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '225',
            "title": 'Medicine and Health in Modern Society',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '234',
            "title": 'Population and Society',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '245',
            "title": 'The Sociology of Emotions',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '247',
            "title": 'Family and Modern Society',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '250',
            "title": 'Social Problems',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '254',
            "title": 'Development and Underdevelopment',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '255',
            "title": 'Gender and the State',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '305',
            "title": 'Socialization',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '307',
            "title": 'Globalization',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '309',
            "title": 'Health and Illness',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '310',
            "title": 'Sociology of Mental Health',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '318',
            "title": 'Sociology of the Media',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '322',
            "title": 'Sociology of Literature',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '325',
            "title": 'Sociology of Science',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '326',
            "title": 'Political Sociology 01',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '341',
            "title": 'Current Problems in Sociology 02',
            "credits": 3.0,
            "choose_from_group": 'Independent Study / Current Problems (max 6 credits combined)',
            "notes": 'Subject to 6-credit maximum combined limit on SOCI 341, 342, 343, 441, 442, 443.',
          },
          {
            "subject": 'SOCI',
            "catalog": '342',
            "title": 'Independent Study 1',
            "credits": 3.0,
            "choose_from_group": 'Independent Study / Current Problems (max 6 credits combined)',
            "notes": 'Subject to 6-credit maximum combined limit on SOCI 341, 342, 343, 441, 442, 443.',
          },
          {
            "subject": 'SOCI',
            "catalog": '343',
            "title": 'Independent Study 2',
            "credits": 3.0,
            "choose_from_group": 'Independent Study / Current Problems (max 6 credits combined)',
            "notes": 'Subject to 6-credit maximum combined limit on SOCI 341, 342, 343, 441, 442, 443.',
          },
          {
            "subject": 'SOCI',
            "catalog": '345',
            "title": 'Topics in Sociology',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
            "notes": 'Topic varies by year.',
          },
          {
            "subject": 'SOCI',
            "catalog": '354',
            "title": 'Dynamics of Industrial Societies',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '388',
            "title": 'Crime',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '430',
            "title": 'Sociology of Citizenship',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '441',
            "title": 'Current Problems in Sociology 03',
            "credits": 3.0,
            "choose_from_group": 'Independent Study / Current Problems (max 6 credits combined)',
            "notes": 'Subject to 6-credit maximum combined limit on SOCI 341, 342, 343, 441, 442, 443.',
          },
          {
            "subject": 'SOCI',
            "catalog": '442',
            "title": 'Independent Reading and Research 01',
            "credits": 3.0,
            "choose_from_group": 'Independent Study / Current Problems (max 6 credits combined)',
            "notes": 'Subject to 6-credit maximum combined limit on SOCI 341, 342, 343, 441, 442, 443.',
          },
          {
            "subject": 'SOCI',
            "catalog": '443',
            "title": 'Independent Reading and Research 02',
            "credits": 3.0,
            "choose_from_group": 'Independent Study / Current Problems (max 6 credits combined)',
            "notes": 'Subject to 6-credit maximum combined limit on SOCI 341, 342, 343, 441, 442, 443.',
          },
          {
            "subject": 'SOCI',
            "catalog": '488',
            "title": 'Punishment and Prisons',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '489',
            "title": 'Gender, Deviance and Social Control',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '495',
            "title": 'Social Problems and Conflicts',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '503',
            "title": 'Surveillance in Modern Society',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": '500-level seminar. Open to Major concentration students in their final year and Honours students.',
          },
          {
            "subject": 'SOCI',
            "catalog": '515',
            "title": 'Medicine and Society',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": '500-level seminar. Open to Major concentration students in their final year and Honours students.',
          },
          {
            "subject": 'SOCI',
            "catalog": '525',
            "title": 'Health Care Systems in Comparative Perspective',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": '500-level seminar. Open to Major concentration students in their final year and Honours students.',
          },
          {
            "subject": 'SOCI',
            "catalog": '535',
            "title": 'Sociology of the Family',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": '500-level seminar. Open to Major concentration students in their final year and Honours students.',
          },
          {
            "subject": 'SOCI',
            "catalog": '538',
            "title": 'Selected Topics in Sociology of Biomedical Knowledge',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": '500-level seminar. Open to Major concentration students in their final year and Honours students.',
          },
          {
            "subject": 'SOCI',
            "catalog": '571',
            "title": 'Deviance and Social Control',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": '500-level seminar. Open to Major concentration students in their final year and Honours students.',
          },
          {
            "subject": 'SOCI',
            "catalog": '595',
            "title": 'Migration Governance and Stratification',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
            "notes": '500-level seminar. Open to Major concentration students in their final year and Honours students.',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'sociology_minor',
    "name": 'Sociology – Minor Concentration',
    "program_type": 'minor',
    "faculty": 'Faculty of Arts',
    "total_credits": 18,
    "description": 'The purpose of the Minor Concentration Sociology is to give the student a basic understanding of the field of sociology. This Minor concentration may be expanded to the Major Concentration Sociology.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/sociology/sociology-minor-concentration-ba/',
    "blocks": [
      {
        "block_key": 'sociology_minor_u1_required',
        "title": 'U1 Required Courses',
        "block_type": 'required',
        "credits_needed": 6,
        "notes": 'Required courses must be taken at McGill.',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'SOCI',
            "catalog": '210',
            "title": 'Sociological Perspectives',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'SOCI',
            "catalog": '211',
            "title": 'Sociological Inquiry',
            "credits": 3.0,
            "is_required": True,
          },
        ],
      },
      {
        "block_key": 'sociology_minor_complementary_300level',
        "title": 'Complementary Courses – 3 credits from Theory/Statistics',
        "block_type": 'choose_credits',
        "credits_needed": 3,
        "notes": 'Choose 3 credits from the following two courses.',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'SOCI',
            "catalog": '330',
            "title": 'Sociological Theory',
            "credits": 3.0,
          },
          {
            "subject": 'SOCI',
            "catalog": '350',
            "title": 'Statistics in Social Research',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'sociology_minor_complementary_9credits',
        "title": 'Complementary Courses – 9 additional credits',
        "block_type": 'choose_credits',
        "credits_needed": 9,
        "notes": 'Choose 9 credits from departmental courses listed below. At least 3 credits must be taken at the 300-level or higher.',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'SOCI',
            "catalog": '213',
            "title": 'Deviance',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '225',
            "title": 'Medicine and Health in Modern Society',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '247',
            "title": 'Family and Modern Society',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '250',
            "title": 'Social Problems',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '305',
            "title": 'Socialization',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'SOCI',
            "catalog": '309',
            "title": 'Health and Illness',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '310',
            "title": 'Sociology of Mental Health',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'SOCI',
            "catalog": '318',
            "title": 'Sociology of the Media',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'SOCI',
            "catalog": '322',
            "title": 'Sociology of Literature',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'SOCI',
            "catalog": '325',
            "title": 'Sociology of Science',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '388',
            "title": 'Crime',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'SOCI',
            "catalog": '430',
            "title": 'Sociology of Citizenship',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": 'Listed under both Institutions/Deviance/Culture and Politics/Social Change.',
          },
          {
            "subject": 'SOCI',
            "catalog": '488',
            "title": 'Punishment and Prisons',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
          },
          {
            "subject": 'SOCI',
            "catalog": '489',
            "title": 'Gender, Deviance and Social Control',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'SOCI',
            "catalog": '495',
            "title": 'Social Problems and Conflicts',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'SOCI',
            "catalog": '503',
            "title": 'Surveillance in Modern Society',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": 'Not currently offered. 500-level seminar; minor students require instructor permission.',
          },
          {
            "subject": 'SOCI',
            "catalog": '515',
            "title": 'Medicine and Society',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": 'Not currently offered. 500-level seminar; minor students require instructor permission.',
          },
          {
            "subject": 'SOCI',
            "catalog": '525',
            "title": 'Health Care Systems in Comparative Perspective',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": 'Not currently offered. 500-level seminar; minor students require instructor permission.',
          },
          {
            "subject": 'SOCI',
            "catalog": '535',
            "title": 'Sociology of the Family',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": 'Not currently offered. 500-level seminar; minor students require instructor permission.',
          },
          {
            "subject": 'SOCI',
            "catalog": '538',
            "title": 'Selected Topics in Sociology of Biomedical Knowledge',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": 'Not currently offered. 500-level seminar; minor students require instructor permission.',
          },
          {
            "subject": 'SOCI',
            "catalog": '571',
            "title": 'Deviance and Social Control',
            "credits": 3.0,
            "choose_from_group": 'Institutions, Deviance, and Culture',
            "notes": 'Not currently offered. 500-level seminar; minor students require instructor permission.',
          },
          {
            "subject": 'SOCI',
            "catalog": '212',
            "title": 'International Migration',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '222',
            "title": 'Urban Sociology',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '234',
            "title": 'Population and Society',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'SOCI',
            "catalog": '245',
            "title": 'The Sociology of Emotions',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '254',
            "title": 'Development and Underdevelopment',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '255',
            "title": 'Gender and the State',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'SOCI',
            "catalog": '307',
            "title": 'Globalization',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'SOCI',
            "catalog": '326',
            "title": 'Political Sociology 01',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '345',
            "title": 'Topics in Sociology',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
            "notes": 'Not currently offered. Topic varies by year.',
          },
          {
            "subject": 'SOCI',
            "catalog": '354',
            "title": 'Dynamics of Industrial Societies',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'SOCI',
            "catalog": '365',
            "title": 'Health and Development',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'SOCI',
            "catalog": '370',
            "title": 'Sociology: Gender and Development',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '386',
            "title": 'Contemporary Social Movements',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '400',
            "title": 'Comparative Migration and Citizenship',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'SOCI',
            "catalog": '424',
            "title": 'Networks and Social Structures',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
            "notes": 'Not currently offered.',
          },
          {
            "subject": 'SOCI',
            "catalog": '446',
            "title": 'Colonialism and Society',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
          },
          {
            "subject": 'SOCI',
            "catalog": '455',
            "title": 'Post-Socialist Societies',
            "credits": 3.0,
            "choose_from_group": 'Politics and Social Change',
            "notes": 'Not currently offered.',
          },
        ],
      },
    ],
  },
]
