"""
McGill Faculty of Arts – Core Humanities: Linguistics, History, Art History, English Literature, Communication Studies, Philosophy
Sub-module of arts_degree_requirements.py
"""

ARTS_HUMANITIES = [
  {
    "program_key": 'linguistics_major',
    "name": 'Linguistics – Major Concentration',
    "program_type": 'major',
    "faculty": 'Faculty of Arts',
    "total_credits": 36,
    "description": 'The Major Concentration in Linguistics focuses on various aspects of linguistics, including theoretical linguistics (phonology, syntax and semantics); experimental linguistics (phonetics, laboratory phonology, language acquisition and psycholinguistics); computational linguistics; linguistic fieldwork and language revitalization; and language variation and change (sociolinguistics, dialectology and historical linguistics).',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/linguistics/linguistics-major-concentration-ba/',
    "blocks": [
      {
        "block_key": 'linguistics_major_required',
        "title": 'Required Courses (15 credits)',
        "block_type": 'required',
        "credits_needed": 15,
        "notes": 'Required courses must be completed at McGill unless Departmental permission is obtained.',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'LING',
            "catalog": '201',
            "title": 'Introduction to Linguistics',
            "credits": 3.0,
            "is_required": True,
            "notes": 'General introduction to linguistics, the scientific study of human language. Covers the core theoretical subfields of linguistics: phonetics, phonology, morphology, syntax, and semantics.',
          },
          {
            "subject": 'LING',
            "catalog": '330',
            "title": 'Phonetics',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Transcription, identification, and production of speech sounds. Introduction to the acoustic properties of speech sounds, acoustic analysis of speech, and auditory phonetics.',
          },
          {
            "subject": 'LING',
            "catalog": '331',
            "title": 'Phonology 1',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Introduction to phonological theory and analysis.',
          },
          {
            "subject": 'LING',
            "catalog": '360',
            "title": 'Introduction to Semantics',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Introduction to the rudiments of semantics, focusing on those aspects of meaning that are invariant across contexts and the ways in which the meaning of a complex expression is determined by the meanings of its constituents.',
          },
          {
            "subject": 'LING',
            "catalog": '371',
            "title": 'Syntax 1',
            "credits": 3.0,
            "is_required": True,
            "notes": 'Introduction to the study of generative syntax of natural languages, emphasizing basic concepts and formalism: phrase structure rules, transformations, and conditions on rules.',
          },
        ],
      },
      {
        "block_key": 'linguistics_major_complementary',
        "title": 'Complementary Courses (21 credits)',
        "block_type": 'multi_group',
        "credits_needed": 21,
        "notes": 'Only 3 credits at the 200 level may count towards complementary credits.',
        "sort_order": 2,
      },
      {
        "block_key": 'linguistics_major_complementary_logic',
        "title": 'Logic/Foundational Courses (3 credits)',
        "block_type": 'choose_credits',
        "group_name": 'Logic Electives',
        "credits_needed": 3,
        "notes": 'Choose 3 credits from the following courses.',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'COMP',
            "catalog": '230',
            "title": 'Logic and Computability',
            "credits": 3.0,
            "choose_from_group": 'Logic Electives',
            "notes": "Propositional Logic, predicate calculus, proof systems, computability Turing machines, Church-Turing thesis, unsolvable problems, completeness, incompleteness, Tarski semantics, uses and misuses of Gödel's theorem.",
          },
          {
            "subject": 'MATH',
            "catalog": '318',
            "title": 'Mathematical Logic',
            "credits": 3.0,
            "choose_from_group": 'Logic Electives',
            "notes": "Propositional logic: truth-tables, formal proof systems, completeness and compactness theorems, Boolean algebras; first-order logic: formal proofs, Gödel's completeness theorem; axiomatic theories; set theory; Cantor's theorem, axiom of choice and Zorn's lemma, Peano arithmetic; Gödel's incompleteness theorem.",
          },
          {
            "subject": 'PHIL',
            "catalog": '210',
            "title": 'Introduction to Deductive Logic 1',
            "credits": 3.0,
            "choose_from_group": 'Logic Electives',
            "notes": 'An introduction to propositional and predicate logic; formalization of arguments, truth tables, systems of deduction, elementary metaresults, and related topics.',
          },
        ],
      },
      {
        "block_key": 'linguistics_major_complementary_ling',
        "title": 'Linguistics Electives (18 credits)',
        "block_type": 'level_elective',
        "credits_needed": 18,
        "notes": "18 credits in Linguistics (LING) chosen according to student's interests. At least 9 of these credits must be at the 400/500 level. Only 3 credits at the 200 level may count towards complementary credits. The catalogue lists INLG 411 as an example of eligible 400-level courses but does not provide an exhaustive list of available courses.",
        "sort_order": 4,
        "courses": [
          {
            "subject": 'INLG',
            "catalog": '411',
            "title": 'Linguistics of Indigenous Languages',
            "credits": 3.0,
            "notes": 'Grammatical properties of Canadian Indigenous languages, focusing on sounds and the sound systems (phonetics and phonology), word formation (morphology), sentence structure and meaning (syntax and semantics), as well as language in use (discourse and pragmatics), and the applications of these topics to language description, documentation, and language pedagogy.',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'linguistics_minor',
    "name": 'Linguistics – Minor Concentration',
    "program_type": 'minor',
    "faculty": 'Faculty of Arts',
    "total_credits": 18,
    "description": 'An 18-credit introduction to the scientific study of human language, focusing on basic Linguistics including phonetics and syntax, theoretical linguistics, experimental linguistics, computational linguistics, linguistic fieldwork and language revitalization, and language variation and change.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/linguistics/linguistics-minor-concentration-ba/',
    "blocks": [
      {
        "block_key": 'linguistics_minor_required',
        "title": 'Required Courses (9 credits)',
        "block_type": 'required',
        "credits_needed": 9,
        "notes": 'Required courses must be completed at McGill unless Departmental permission is obtained.',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'LING',
            "catalog": '201',
            "title": 'Introduction to Linguistics',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'LING',
            "catalog": '330',
            "title": 'Phonetics',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'LING',
            "catalog": '371',
            "title": 'Syntax 1',
            "credits": 3.0,
            "is_required": True,
          },
        ],
      },
      {
        "block_key": 'linguistics_minor_complementary',
        "title": 'Complementary Courses (9 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 9,
        "notes": "9 credits in Linguistics chosen according to student's interests. Constraint: 6 credits must be at 300 level or higher. Only 3 credits at the 200 level may count. Students taking LING 360 (Introduction to Semantics) may count one of the prerequisite courses (COMP 230, MATH 318, or PHIL 210) toward this requirement.",
        "sort_order": 2,
        "courses": [
          {
            "subject": 'INLG',
            "catalog": '411',
            "title": 'Linguistics of Indigenous Languages',
            "credits": 3.0,
            "notes": 'Example complementary course listed in catalogue',
          },
          {
            "subject": 'COMP',
            "catalog": '230',
            "title": 'Logic and Computability',
            "credits": 3.0,
            "notes": 'May count toward complementary requirement if LING 360 (Introduction to Semantics) is taken as prerequisite',
          },
          {
            "subject": 'MATH',
            "catalog": '318',
            "title": 'Mathematical Logic',
            "credits": 3.0,
            "notes": 'May count toward complementary requirement if LING 360 (Introduction to Semantics) is taken as prerequisite',
          },
          {
            "subject": 'PHIL',
            "catalog": '210',
            "title": 'Introduction to Deductive Logic 1',
            "credits": 3.0,
            "notes": 'May count toward complementary requirement if LING 360 (Introduction to Semantics) is taken as prerequisite',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'history_major',
    "name": 'History – Major Concentration',
    "program_type": 'major',
    "faculty": 'Faculty of Arts',
    "total_credits": 36,
    "description": 'The Major Concentration History is a highly flexible program that emphasizes both breadth and depth, while introducing students to different historical theories and methodologies. Students select from a wide variety of courses on diverse cultures and societies around the world from antiquity to contemporary times, and also on thematic subjects such as history and sexuality, imperialism and colonialism, histories of science, environmental history, and the history of thought and ideas. Students design their program to match their geographic, chronological, thematic or methodological interests.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/history-classical-studies/history-major-concentration-ba/',
    "blocks": [
      {
        "block_key": 'history_major_distribution',
        "title": 'Distribution Requirement (9 credits: 3 from Group A, 3 from Group B, 3 from Group C)',
        "block_type": 'multi_group',
        "credits_needed": 9,
        "notes": '3 credits must come from Group A, 3 from Group B, and 3 from Group C. Cognate courses may not be used to satisfy the Distribution requirement. The same course may be used to satisfy both a Distribution and Temporal Breadth requirement.',
        "sort_order": 1,
      },
      {
        "block_key": 'history_major_group_a',
        "title": 'Group A (3 credits)',
        "block_type": 'group',
        "group_name": 'Group A',
        "credits_needed": 3,
        "sort_order": 2,
        "courses": [
          {
            "subject": 'HIST',
            "catalog": '202',
            "title": 'Survey: Canada to 1867.',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'HIST',
            "catalog": '203',
            "title": 'Survey: Canada since 1867.',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'HIST',
            "catalog": '211',
            "title": 'American History to 1865.',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'HIST',
            "catalog": '212',
            "title": 'Medieval Europe.',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'HIST',
            "catalog": '214',
            "title": 'Early Modern Europe.',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'HIST',
            "catalog": '215',
            "title": 'Modern Europe.',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'HIST',
            "catalog": '216',
            "title": 'Introduction to Russian History.',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'HIST',
            "catalog": '221',
            "title": 'United States since 1865.',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'HIST',
            "catalog": '226',
            "title": 'East Central and Southeastern Europe in 20th Century.',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'HIST',
            "catalog": '250',
            "title": 'Making Great Britain and Ireland.',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
        ],
      },
      {
        "block_key": 'history_major_group_b',
        "title": 'Group B (3 credits)',
        "block_type": 'group',
        "group_name": 'Group B',
        "credits_needed": 3,
        "sort_order": 3,
        "courses": [
          {
            "subject": 'HIST',
            "catalog": '200',
            "title": 'Introduction to African History.',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'HIST',
            "catalog": '201',
            "title": 'Modern African History.',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'HIST',
            "catalog": '205',
            "title": 'Ancient Mediterranean History.',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'HIST',
            "catalog": '206',
            "title": 'Indian Ocean World History.',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'HIST',
            "catalog": '208',
            "title": 'Introduction to East Asian History.',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'HIST',
            "catalog": '209',
            "title": 'Introduction to South Asian History.',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'HIST',
            "catalog": '210',
            "title": 'Introduction to Latin American History.',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'HIST',
            "catalog": '218',
            "title": 'Modern East Asian History.',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'HIST',
            "catalog": '275',
            "title": 'Ancient Roman History.',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
        ],
      },
      {
        "block_key": 'history_major_group_c',
        "title": 'Group C (3 credits)',
        "block_type": 'group',
        "group_name": 'Group C',
        "credits_needed": 3,
        "sort_order": 4,
        "courses": [
          {
            "subject": 'HIST',
            "catalog": '207',
            "title": 'Jewish History: 400 B.C.E. to 1000.',
            "credits": 3.0,
            "choose_from_group": 'Group C',
          },
          {
            "subject": 'HIST',
            "catalog": '213',
            "title": 'World History, 600-2000.',
            "credits": 3.0,
            "choose_from_group": 'Group C',
          },
          {
            "subject": 'HIST',
            "catalog": '219',
            "title": 'Jewish History: 1000 - 2000.',
            "credits": 3.0,
            "choose_from_group": 'Group C',
          },
          {
            "subject": 'HIST',
            "catalog": '222',
            "title": 'History of Pandemics.',
            "credits": 3.0,
            "choose_from_group": 'Group C',
          },
          {
            "subject": 'HIST',
            "catalog": '223',
            "title": 'Indigenous Peoples and Empires.',
            "credits": 3.0,
            "choose_from_group": 'Group C',
          },
          {
            "subject": 'HIST',
            "catalog": '224',
            "title": 'Introduction to the African Diaspora.',
            "credits": 3.0,
            "choose_from_group": 'Group C',
          },
          {
            "subject": 'HIST',
            "catalog": '238',
            "title": 'Histories of Science.',
            "credits": 3.0,
            "choose_from_group": 'Group C',
          },
          {
            "subject": 'HIST',
            "catalog": '240',
            "title": 'Modern History of Islamic Movements.',
            "credits": 3.0,
            "choose_from_group": 'Group C',
          },
        ],
      },
      {
        "block_key": 'history_major_electives',
        "title": 'Remaining HIST or Cognate Electives (27 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 27,
        "notes": '36 credits total of HIST or approved cognate courses. 9 credits satisfied by the Distribution Requirement (Groups A, B, C); remaining 27 credits may be any HIST or cognate courses subject to: (1) Temporal Breadth: at least 3 credits before 1800 and at least 3 credits after 1800 (HIST 299 may not count toward Temporal Breadth); (2) Level: maximum 15 credits at the 200-level; minimum 6 credits at the 400- or 500-level (at most 3 credits of HIST 498 or HIST 499 may count toward this minimum). Cognate courses may not satisfy the Distribution requirement. AP/IB credits may not be included in credit requirements.',
        "sort_order": 5,
      },
    ],
  },
  {
    "program_key": 'history_minor',
    "name": 'History – Minor Concentration',
    "program_type": 'minor',
    "faculty": 'Faculty of Arts',
    "total_credits": 18,
    "description": 'Introduces students to diverse cultures and societies from antiquity to today. Expandable to a Major Concentration.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/history-classical-studies/history-minor-concentration-ba/',
    "blocks": [
      {
        "block_key": 'history_minor_complementary',
        "title": 'Complementary Courses (18 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 18,
        "notes": '18 credits of history courses (HIST or Cognate courses). No more than 6 credits may be at the 200-level. Cognate courses (CLAS, ISLA, JWST, RELG) limited to maximum 3 credits total. Additional courses may be submitted for consideration to the Undergraduate Program Director.',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'CLAS',
            "catalog": '303',
            "title": 'Ancient Greek Religion',
            "credits": 3.0,
          },
          {
            "subject": 'CLAS',
            "catalog": '304',
            "title": 'Ancient Greek Democracy',
            "credits": 3.0,
          },
          {
            "subject": 'CLAS',
            "catalog": '305',
            "title": 'Roman Religion',
            "credits": 3.0,
          },
          {
            "subject": 'CLAS',
            "catalog": '406',
            "title": 'Greek and Roman Historiography',
            "credits": 3.0,
          },
          {
            "subject": 'ISLA',
            "catalog": '311',
            "title": 'History of the City-Islamic World',
            "credits": 3.0,
          },
          {
            "subject": 'ISLA',
            "catalog": '315',
            "title": 'Ottoman State and Society to 1839',
            "credits": 3.0,
          },
          {
            "subject": 'ISLA',
            "catalog": '355',
            "title": 'Modern History of the Middle East',
            "credits": 3.0,
          },
          {
            "subject": 'ISLA',
            "catalog": '365',
            "title": "Middle East Since the 1970's",
            "credits": 3.0,
          },
          {
            "subject": 'ISLA',
            "catalog": '375',
            "title": 'Sufi Women',
            "credits": 3.0,
          },
          {
            "subject": 'ISLA',
            "catalog": '410',
            "title": 'History: Middle-East 1798-1918',
            "credits": 3.0,
          },
          {
            "subject": 'ISLA',
            "catalog": '411',
            "title": 'History: Middle-East 1918-1945',
            "credits": 3.0,
          },
          {
            "subject": 'ISLA',
            "catalog": '421',
            "title": 'Islamic Culture - Indian Subcontinent',
            "credits": 3.0,
          },
          {
            "subject": 'ISLA',
            "catalog": '511',
            "title": 'Medieval Islam, 10th-12th Century',
            "credits": 3.0,
          },
          {
            "subject": 'ISLA',
            "catalog": '515',
            "title": 'The Medieval School in Islam',
            "credits": 3.0,
          },
          {
            "subject": 'ISLA',
            "catalog": '516',
            "title": 'Medieval Islam, 13th-15th Century',
            "credits": 3.0,
          },
          {
            "subject": 'ISLA',
            "catalog": '530',
            "title": 'Advanced Sufism',
            "credits": 3.0,
          },
          {
            "subject": 'ISLA',
            "catalog": '580',
            "title": 'Topics in Ottoman History',
            "credits": 3.0,
          },
          {
            "subject": 'JWST',
            "catalog": '240',
            "title": 'The Holocaust',
            "credits": 3.0,
          },
          {
            "subject": 'JWST',
            "catalog": '245',
            "title": 'Jewish Life in the Islamic World',
            "credits": 3.0,
          },
          {
            "subject": 'JWST',
            "catalog": '303',
            "title": 'The Soviet Jewish Experience',
            "credits": 3.0,
          },
          {
            "subject": 'JWST',
            "catalog": '312',
            "title": 'Modern Jewish History',
            "credits": 3.0,
          },
          {
            "subject": 'JWST',
            "catalog": '334',
            "title": 'Jews and Muslims: A Modern History',
            "credits": 3.0,
          },
          {
            "subject": 'JWST',
            "catalog": '348',
            "title": 'Modern Jewish Studies',
            "credits": 3.0,
          },
          {
            "subject": 'JWST',
            "catalog": '365',
            "title": 'Modern Jewish Ideologies',
            "credits": 3.0,
          },
          {
            "subject": 'JWST',
            "catalog": '366',
            "title": 'History of Zionism',
            "credits": 3.0,
          },
          {
            "subject": 'JWST',
            "catalog": '371',
            "title": 'Jews and the City',
            "credits": 3.0,
          },
          {
            "subject": 'RELG',
            "catalog": '326',
            "title": 'Christians in the Roman World',
            "credits": 3.0,
          },
        ],
      },
    ],
  },
  {
    "program_key": 'art_history_major',
    "name": 'Art History – Major Concentration',
    "program_type": 'major',
    "faculty": 'Faculty of Arts',
    "total_credits": 36,
    "description": 'Comprehensive study of visual arts, material culture, and architecture from antiquity to the present, primarily focusing on Europe and North America. Concentrates on analysis of forms of visual and material culture from ancient to contemporary times and provides a grounding in diverse fields and methods of the discipline.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/art-history-communication-studies/art-history-major-concentration-ba/',
    "blocks": [
      {
        "block_key": 'art_history_major_intro_methods',
        "title": 'Introductory Methods, Theories, and Practices (3–15 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 3,
        "notes": 'Select 3–15 credits as an introduction to methods, theories, and practices in diverse fields of the discipline.',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'ARTH',
            "catalog": '302',
            "title": 'Aspects of Canadian Art',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '305',
            "title": 'Methods in Art History',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '315',
            "title": 'Indigenous Art and Culture',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '339',
            "title": 'Critical Issues - Contemporary Art',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '357',
            "title": 'Early Chinese Art',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'art_history_major_complementary',
        "title": 'Complementary Courses (21–33 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 21,
        "notes": 'Select 21–33 credits from departmental course offerings. Maximum 12 credits may be at the 200 level. Minimum 3 credits must be at the 400 level or above (excluding ARTH 490 Museum Internship). Courses in studio practice cannot be counted toward the Major concentration.',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'ARTH',
            "catalog": '200',
            "title": 'Introduction to Art History 1',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '202',
            "title": 'Introduction to Contemporary Art',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '204',
            "title": 'Introduction to Medieval Art and Architecture',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '205',
            "title": 'Introduction to Modern Art',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '207',
            "title": 'Introduction Early Modern Art 1400-1700',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '209',
            "title": 'Introduction to Ancient Art and Architecture',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '215',
            "title": 'Introduction to East Asian Art',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '223',
            "title": 'Introduction Italian Renaissance Art 1300-1500',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '225',
            "title": 'Introduction to Seventeenth - Century Art',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '226',
            "title": 'Introduction to Eighteenth-Century Art and Architecture',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '300',
            "title": 'Canadian Art to 1914',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '310',
            "title": 'Postcolonialism',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '314',
            "title": 'The Medieval City',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '321',
            "title": 'Visual Culture of the Dutch Republic',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '323',
            "title": 'Realism and Impressionism',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '325',
            "title": 'Visual Culture Renaissance Venice',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '326',
            "title": 'Studies in Manuscript and Print Culture',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '336',
            "title": 'Art Now',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '352',
            "title": 'Feminism in Art and Art History',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '353',
            "title": 'Selected Topics in Art History 1',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '354',
            "title": 'Selected Topics Art History 2',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '360',
            "title": 'Studies in the Photographic',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '368',
            "title": 'Studies in Northern Renaissance Art 01',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '411',
            "title": 'Canadian Art and Race',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '420',
            "title": 'Selected Topics in Art and Architecture 1',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '421',
            "title": 'Selected Topics in Art and Architecture 2',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '422',
            "title": 'Selected Topics in Art and Architecture 3',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '425',
            "title": 'Arts of Medieval Spain',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '430',
            "title": 'Concepts - Discipline Art History',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '435',
            "title": 'Early Modern Visual Culture',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '440',
            "title": 'The Body and Visual Culture',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '447',
            "title": 'Independent Research Course',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '473',
            "title": 'Studies in 17th and Early 18th Century Art 04',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '474',
            "title": 'Studies in Later 18th and 19th Century Art 03',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '490',
            "title": 'Museum Internship',
            "credits": 3.0,
            "notes": 'Excluded from the minimum 3 credits at 400-level requirement.',
          },
          {
            "subject": 'ARTH',
            "catalog": '501',
            "title": 'Advanced Topics in Art History and Visual Culture',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '502',
            "title": 'Advanced Topics in Art and Architectural History',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'art_history_major_related_optional',
        "title": 'Related Courses (Optional)',
        "block_type": 'choose_credits',
        "credits_needed": 0,
        "notes": 'In addition to architectural courses given by the Department, program students are encouraged to consider courses from the School of Architecture, the departments of East Asian Studies and Philosophy which may, upon consultation with the Department, be regarded as fulfilling part of the requirements.',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'ARCH',
            "catalog": '250',
            "title": 'Architectural History 1',
            "credits": 3.0,
            "notes": 'Optional; may be regarded as fulfilling part of requirements upon consultation with Department.',
          },
          {
            "subject": 'ARCH',
            "catalog": '251',
            "title": 'Architectural History 2',
            "credits": 3.0,
            "notes": 'Optional; may be regarded as fulfilling part of requirements upon consultation with Department.',
          },
          {
            "subject": 'PHIL',
            "catalog": '336',
            "title": 'Aesthetics',
            "credits": 3.0,
            "notes": 'Optional; may be regarded as fulfilling part of requirements upon consultation with Department.',
          },
          {
            "subject": 'PHIL',
            "catalog": '436',
            "title": 'Aesthetics 2',
            "credits": 3.0,
            "notes": 'Optional; may be regarded as fulfilling part of requirements upon consultation with Department.',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'art_history_minor',
    "name": 'Art History – Minor Concentration',
    "program_type": 'minor',
    "faculty": 'Faculty of Arts',
    "total_credits": 18,
    "description": 'The Minor Concentration in Art History provides an introduction to the study of diverse artistic traditions from ancient to contemporary times. It is expandable to the Major Concentration Art History.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/art-history-communication-studies/art-history-minor-concentration-ba/',
    "blocks": [
      {
        "block_key": 'art_history_minor_complementary',
        "title": 'Complementary Courses (18 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 18,
        "notes": 'Students must choose 18 credits total. At least 9 credits must be at the 300-level or above. Courses in studio practice cannot be counted towards the Minor Concentration. Students are encouraged to consult with the Department about courses from the School of Architecture, Department of East Asian Studies, and Department of Philosophy.',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'ARTH',
            "catalog": '200',
            "title": 'Introduction to Art History 1.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '202',
            "title": 'Introduction to Contemporary Art.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '204',
            "title": 'Introduction to Medieval Art and Architecture.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '205',
            "title": 'Introduction to Modern Art.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '207',
            "title": 'Introduction Early Modern Art 1400-1700.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '209',
            "title": 'Introduction to Ancient Art and Architecture.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '215',
            "title": 'Introduction to East Asian Art.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '223',
            "title": 'Introduction Italian Renaissance Art 1300-1500.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '225',
            "title": 'Introduction to Seventeenth - Century Art.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '226',
            "title": 'Introduction to Eighteenth-Century Art and Architecture.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '300',
            "title": 'Canadian Art to 1914.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '302',
            "title": 'Aspects of Canadian Art.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '305',
            "title": 'Methods in Art History.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '310',
            "title": 'Postcolonialism.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '314',
            "title": 'The Medieval City.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '315',
            "title": 'Indigenous Art and Culture.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '321',
            "title": 'Visual Culture of the Dutch Republic.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '323',
            "title": 'Realism and Impressionism.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '325',
            "title": 'Visual Culture Renaissance Venice.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '326',
            "title": 'Studies in Manuscript and Print Culture.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '336',
            "title": 'Art Now.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '339',
            "title": 'Critical Issues - Contemporary Art.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '352',
            "title": 'Feminism in Art and Art History.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '353',
            "title": 'Selected Topics in Art History 1.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '354',
            "title": 'Selected Topics Art History 2.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '357',
            "title": 'Early Chinese Art.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '360',
            "title": 'Studies in the Photographic.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '368',
            "title": 'Studies in Northern Renaissance Art 01.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '411',
            "title": 'Canadian Art and Race.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '420',
            "title": 'Selected Topics in Art and Architecture 1.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '421',
            "title": 'Selected Topics in Art and Architecture 2.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '422',
            "title": 'Selected Topics in Art and Architecture 3.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '425',
            "title": 'Arts of Medieval Spain.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '430',
            "title": 'Concepts - Discipline Art History.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '435',
            "title": 'Early Modern Visual Culture.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '440',
            "title": 'The Body and Visual Culture.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '447',
            "title": 'Independent Research Course.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '473',
            "title": 'Studies in 17th and Early 18th Century Art 04.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '474',
            "title": 'Studies in Later 18th and 19th Century Art 03.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '490',
            "title": 'Museum Internship',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '501',
            "title": 'Advanced Topics in Art History and Visual Culture.',
            "credits": 3.0,
          },
          {
            "subject": 'ARTH',
            "catalog": '502',
            "title": 'Advanced Topics in Art and Architectural History.',
            "credits": 3.0,
          },
          {
            "subject": 'ARCH',
            "catalog": '250',
            "title": 'Architectural History 1.',
            "credits": 3.0,
            "recommended": True,
            "recommendation_reason": 'Encouraged complementary course from School of Architecture',
          },
          {
            "subject": 'ARCH',
            "catalog": '251',
            "title": 'Architectural History 2.',
            "credits": 3.0,
            "recommended": True,
            "recommendation_reason": 'Encouraged complementary course from School of Architecture',
          },
          {
            "subject": 'PHIL',
            "catalog": '336',
            "title": 'Aesthetics.',
            "credits": 3.0,
            "recommended": True,
            "recommendation_reason": 'Encouraged complementary course from Department of Philosophy',
          },
          {
            "subject": 'PHIL',
            "catalog": '436',
            "title": 'Aesthetics 2.',
            "credits": 3.0,
            "recommended": True,
            "recommendation_reason": 'Encouraged complementary course from Department of Philosophy',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'english_literature_major',
    "name": 'English – Literature Major Concentration',
    "program_type": 'major',
    "faculty": 'Faculty of Arts',
    "total_credits": 36,
    "description": 'The Literature option provides a grounding in the basic texts and methods of the discipline as well as wide acquaintance with substantial areas of the field.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/english/english-literature-major-concentration-ba/',
    "blocks": [
      {
        "block_key": 'english_literature_major_required',
        "title": 'Required Courses (9 credits)',
        "block_type": 'required',
        "credits_needed": 9,
        "notes": 'These courses should be taken in the first two terms of the program.',
        "sort_order": 1,
        "courses": [
          {
            "subject": 'ENGL',
            "catalog": '202',
            "title": 'Departmental Survey of English Literature 1.',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'ENGL',
            "catalog": '203',
            "title": 'Departmental Survey of English Literature 2.',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'ENGL',
            "catalog": '311',
            "title": 'Poetics.',
            "credits": 3.0,
            "is_required": True,
          },
        ],
      },
      {
        "block_key": 'english_literature_major_canadian_lit',
        "title": 'Canadian Literature (3 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 3,
        "notes": '3 credits from a list of Canadian Literature courses.',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'ENGL',
            "catalog": '228',
            "title": 'Canadian Literature 1.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '229',
            "title": 'Canadian Literature 2.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '327',
            "title": 'Canadian Prose Fiction 1.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '328',
            "title": 'Development of Canadian Poetry 1.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '333',
            "title": 'Development of Canadian Poetry 2.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '409',
            "title": 'Studies in a Canadian Author.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '410',
            "title": 'Theme or Movement Canadian Literature.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '411',
            "title": 'Studies in Canadian Fiction.',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'english_literature_major_theory',
        "title": 'Theory, Criticism and Methods (3 credits)',
        "block_type": 'choose_credits',
        "credits_needed": 3,
        "notes": '3 credits of Theory, Criticism, and Methods courses from the complementary list or with the permission of your department adviser.',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'ENGL',
            "catalog": '317',
            "title": 'Literary and Cultural Theory',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '318',
            "title": 'Literary and Cultural Methods',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '319',
            "title": 'Literary and Cultural Criticism',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '322',
            "title": 'Theories of the Text.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '346',
            "title": 'Materiality and Sociology of Text.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '352',
            "title": 'Theories of Difference.',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'english_literature_major_areas1',
        "title": 'Areas of English Literature – Early (6 credits)',
        "block_type": 'multi_group',
        "credits_needed": 6,
        "notes": '6 credits, 3 credits each from two of the following areas: Backgrounds of English Literature, Old English, Medieval, Renaissance.',
        "sort_order": 4,
      },
      {
        "block_key": 'english_literature_major_areas1_backgrounds',
        "title": 'Backgrounds of English Literature',
        "block_type": 'group',
        "group_name": 'Backgrounds of English Literature',
        "sort_order": 5,
        "courses": [
          {
            "subject": 'ENGL',
            "catalog": '347',
            "title": 'Great Writings of Europe 1.',
            "credits": 3.0,
            "choose_from_group": 'Backgrounds of English Literature',
          },
          {
            "subject": 'ENGL',
            "catalog": '348',
            "title": 'Great Writings of Europe 2.',
            "credits": 3.0,
            "choose_from_group": 'Backgrounds of English Literature',
          },
          {
            "subject": 'ENGL',
            "catalog": '349',
            "title": 'English Literature and Folklore 1.',
            "credits": 3.0,
            "choose_from_group": 'Backgrounds of English Literature',
          },
        ],
      },
      {
        "block_key": 'english_literature_major_areas1_old_english',
        "title": 'Old English',
        "block_type": 'group',
        "group_name": 'Old English',
        "sort_order": 6,
        "courses": [
          {
            "subject": 'ENGL',
            "catalog": '342',
            "title": 'Introduction to Old English.',
            "credits": 3.0,
            "choose_from_group": 'Old English',
          },
          {
            "subject": 'ENGL',
            "catalog": '349',
            "title": 'English Literature and Folklore 1.',
            "credits": 3.0,
            "choose_from_group": 'Old English',
          },
          {
            "subject": 'ENGL',
            "catalog": '452',
            "title": 'Studies in Old English.',
            "credits": 3.0,
            "choose_from_group": 'Old English',
          },
        ],
      },
      {
        "block_key": 'english_literature_major_areas1_medieval',
        "title": 'Medieval',
        "block_type": 'group',
        "group_name": 'Medieval',
        "sort_order": 7,
        "courses": [
          {
            "subject": 'ENGL',
            "catalog": '337',
            "title": 'Theme or Genre in Medieval Literature.',
            "credits": 3.0,
            "choose_from_group": 'Medieval',
          },
          {
            "subject": 'ENGL',
            "catalog": '349',
            "title": 'English Literature and Folklore 1.',
            "credits": 3.0,
            "choose_from_group": 'Medieval',
          },
          {
            "subject": 'ENGL',
            "catalog": '356',
            "title": 'Middle English.',
            "credits": 3.0,
            "choose_from_group": 'Medieval',
          },
          {
            "subject": 'ENGL',
            "catalog": '357',
            "title": 'Chaucer.',
            "credits": 3.0,
            "choose_from_group": 'Medieval',
          },
          {
            "subject": 'ENGL',
            "catalog": '456',
            "title": 'Middle English.',
            "credits": 3.0,
            "choose_from_group": 'Medieval',
          },
        ],
      },
      {
        "block_key": 'english_literature_major_areas1_renaissance',
        "title": 'Renaissance',
        "block_type": 'group',
        "group_name": 'Renaissance',
        "sort_order": 8,
        "courses": [
          {
            "subject": 'ENGL',
            "catalog": '305',
            "title": 'Renaissance English Literature 1.',
            "credits": 3.0,
            "choose_from_group": 'Renaissance',
          },
          {
            "subject": 'ENGL',
            "catalog": '307',
            "title": 'Renaissance English Literature 2.',
            "credits": 3.0,
            "choose_from_group": 'Renaissance',
          },
          {
            "subject": 'ENGL',
            "catalog": '308',
            "title": 'English Renaissance Drama 1.',
            "credits": 3.0,
            "choose_from_group": 'Renaissance',
          },
          {
            "subject": 'ENGL',
            "catalog": '315',
            "title": 'Shakespeare.',
            "credits": 3.0,
            "choose_from_group": 'Renaissance',
          },
          {
            "subject": 'ENGL',
            "catalog": '316',
            "title": 'Milton.',
            "credits": 3.0,
            "choose_from_group": 'Renaissance',
          },
          {
            "subject": 'ENGL',
            "catalog": '349',
            "title": 'English Literature and Folklore 1.',
            "credits": 3.0,
            "choose_from_group": 'Renaissance',
          },
          {
            "subject": 'ENGL',
            "catalog": '400',
            "title": 'Earlier English Renaissance.',
            "credits": 3.0,
            "choose_from_group": 'Renaissance',
          },
          {
            "subject": 'ENGL',
            "catalog": '401',
            "title": 'Studies in the 17th Century.',
            "credits": 3.0,
            "choose_from_group": 'Renaissance',
          },
          {
            "subject": 'ENGL',
            "catalog": '416',
            "title": 'Studies in Shakespeare.',
            "credits": 3.0,
            "choose_from_group": 'Renaissance',
          },
        ],
      },
      {
        "block_key": 'english_literature_major_areas2',
        "title": 'Areas of English Literature – Later (6 credits)',
        "block_type": 'multi_group',
        "credits_needed": 6,
        "notes": '6 credits, 3 credits each from two of the following areas: Restoration, 18th Century, Romantic, Victorian, 19th Century American. NOTE: This block is incomplete due to page truncation. Only Restoration area courses were fully captured; 18th Century and subsequent areas were cut off.',
        "sort_order": 9,
      },
      {
        "block_key": 'english_literature_major_areas2_restoration',
        "title": 'Restoration',
        "block_type": 'group',
        "group_name": 'Restoration',
        "sort_order": 10,
        "courses": [
          {
            "subject": 'ENGL',
            "catalog": '302',
            "title": 'Restoration and 18th C. English Literature 1.',
            "credits": 3.0,
            "choose_from_group": 'Restoration',
          },
          {
            "subject": 'ENGL',
            "catalog": '444',
            "title": 'Studies in Women Authors.',
            "credits": 3.0,
            "choose_from_group": 'Restoration',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'english_literature_minor',
    "name": 'English – Literature Minor Concentration',
    "program_type": 'minor',
    "faculty": 'Faculty of Arts',
    "total_credits": 18,
    "description": 'An 18-credit introduction to English literature across periods and genres. The Minor Concentration English - Literature may be expanded to the Major Concentration English - Literature.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/english/english-literature-minor-concentration-ba/',
    "blocks": [
      {
        "block_key": 'english_literature_minor_required',
        "title": 'Required Courses',
        "block_type": 'required',
        "credits_needed": 6,
        "sort_order": 1,
        "courses": [
          {
            "subject": 'ENGL',
            "catalog": '202',
            "title": 'Departmental Survey of English Literature 1.',
            "credits": 3.0,
            "is_required": True,
          },
          {
            "subject": 'ENGL',
            "catalog": '203',
            "title": 'Departmental Survey of English Literature 2.',
            "credits": 3.0,
            "is_required": True,
          },
        ],
      },
      {
        "block_key": 'english_literature_minor_major_author',
        "title": 'Major Author',
        "block_type": 'choose_credits',
        "credits_needed": 3,
        "notes": '3 credits on a Major Author',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'ENGL',
            "catalog": '315',
            "title": 'Shakespeare.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '316',
            "title": 'Milton.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '357',
            "title": 'Chaucer.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '409',
            "title": 'Studies in a Canadian Author.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '416',
            "title": 'Studies in Shakespeare.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '417',
            "title": 'A Major English Poet.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '418',
            "title": 'A Major Modernist Writer.',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'english_literature_minor_pre1800',
        "title": 'Pre-1800',
        "block_type": 'choose_credits',
        "credits_needed": 3,
        "notes": '3 credits from a list of pre-1800 literature courses',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'ENGL',
            "catalog": '301',
            "title": 'Earlier 18th Century Novel.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '302',
            "title": 'Restoration and 18th C. English Literature 1.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '304',
            "title": 'Later Eighteenth Century Novel.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '305',
            "title": 'Renaissance English Literature 1.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '307',
            "title": 'Renaissance English Literature 2.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '308',
            "title": 'English Renaissance Drama 1.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '315',
            "title": 'Shakespeare.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '316',
            "title": 'Milton.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '342',
            "title": 'Introduction to Old English.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '347',
            "title": 'Great Writings of Europe 1.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '348',
            "title": 'Great Writings of Europe 2.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '349',
            "title": 'English Literature and Folklore 1.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '356',
            "title": 'Middle English.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '357',
            "title": 'Chaucer.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '400',
            "title": 'Earlier English Renaissance.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '401',
            "title": 'Studies in the 17th Century.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '403',
            "title": 'Studies in the 18th Century.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '416',
            "title": 'Studies in Shakespeare.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '444',
            "title": 'Studies in Women Authors.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '452',
            "title": 'Studies in Old English.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '456',
            "title": 'Middle English.',
            "credits": 3.0,
          },
        ],
      },
      {
        "block_key": 'english_literature_minor_additional',
        "title": 'Additional Literature',
        "block_type": 'choose_credits',
        "credits_needed": 6,
        "notes": '6 additional credits from ENGL offerings in Literature. Any ENGL course not on these Literature lists, such as courses in Cultural Studies, may not count.',
        "sort_order": 4,
        "courses": [
          {
            "subject": 'ENGL',
            "catalog": '199',
            "title": 'FYS: Form and Representation.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '204',
            "title": 'English Literature and the Bible.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '237',
            "title": 'Introduction to Study of a Literary Form.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '295',
            "title": '21C and 20C Literature and Culture',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '297',
            "title": 'Special Topics of Literary Study.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '343',
            "title": 'Literature and Science 1.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '345',
            "title": 'Literature and Society.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '354',
            "title": 'Sexuality and Representation.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '364',
            "title": 'Creative Writing.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '385',
            "title": 'Topics in Literature and Film.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '394',
            "title": 'Popular Literary Forms.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '421',
            "title": 'African Literature.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '424',
            "title": 'Irish Literature.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '437',
            "title": 'Studies in Literary Form.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '438',
            "title": 'Studies in Literary Form.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '440',
            "title": 'First Nations and Inuit Literature and Media.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '444',
            "title": 'Studies in Women Authors.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '447',
            "title": 'Crosscurrents/English Literature and European Literature 1.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '460',
            "title": 'Studies in Literary Theory.',
            "credits": 3.0,
          },
          {
            "subject": 'ENGL',
            "catalog": '461',
            "title": 'Studies in Literary Theory 2.',
            "credits": 3.0,
          },
        ],
      },
    ],
  },
  {
    "program_key": 'communication_studies_minor',
    "name": 'Communication Studies – Minor Concentration',
    "program_type": 'minor',
    "faculty": 'Faculty of Arts',
    "total_credits": 18,
    "description": 'The Minor Concentration Communication Studies provides undergraduate students with a critical understanding of the role that communications media and communication technologies play in a society. It offers students intellectually challenging and innovative instruction in key traditions of Communications and Media Studies and new theoretical and methodological practices being developed in the field.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/art-history-communication-studies/communication-studies-minor-concentration-ba/',
    "blocks": [
      {
        "block_key": 'communication_studies_minor_required',
        "title": 'Required Course (3 credits)',
        "block_type": 'required',
        "credits_needed": 3,
        "sort_order": 1,
        "courses": [
          {
            "subject": 'COMS',
            "catalog": '210',
            "title": 'Introduction to Communication Studies',
            "credits": 3.0,
            "is_required": True,
          },
        ],
      },
      {
        "block_key": 'communication_studies_minor_complementary',
        "title": 'Complementary Courses (15 credits)',
        "block_type": 'choose_courses',
        "credits_needed": 15,
        "courses_needed": 5,
        "notes": 'Five courses in Communication Studies selected from the list below',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'COMS',
            "catalog": '200',
            "title": 'History of Communication',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '230',
            "title": 'Communication and Democracy',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '300',
            "title": 'Media and Modernity in the 20th Century',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '301',
            "title": 'Core Concepts in Critical Theory',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '310',
            "title": 'Media and Feminist Studies',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '320',
            "title": 'Media and Empire',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '330',
            "title": 'Media in Cultural Life',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '340',
            "title": 'New Media',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '350',
            "title": 'Sound Culture',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '354',
            "title": 'Media Studies of Crime',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '355',
            "title": 'Media Governance',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '361',
            "title": 'Selected Topics Communication Studies 1',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '362',
            "title": 'Selected Topics Communication Studies 2',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '400',
            "title": 'Critical Theory Seminar',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '410',
            "title": 'Cultures in Visualization',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '411',
            "title": 'Disability, Technology and Communication',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '425',
            "title": 'Urban Culture and Everyday Life',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '435',
            "title": 'Advanced Issues in Media Governance',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '490',
            "title": 'Special Topics in History and Theory of Media',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '491',
            "title": 'Special Topics in Communications Studies',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '492',
            "title": 'Power, Difference and Justice',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '495',
            "title": 'Directed Reading',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '497',
            "title": 'Independent Study',
            "credits": 3.0,
          },
          {
            "subject": 'COMS',
            "catalog": '510',
            "title": 'Canadian Broadcasting Policy',
            "credits": 3.0,
          },
        ],
      },
    ],
  },
  {
    "program_key": 'philosophy_major',
    "name": 'Philosophy – Major Concentration',
    "program_type": 'major',
    "faculty": 'Faculty of Arts',
    "total_credits": 36,
    "description": 'Covers metaphysics, epistemology, ethics, logic, and the history of philosophy.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/philosophy/philosophy-major-concentration-ba/',
    "blocks": [
      {
        "block_key": 'philosophy_major_required',
        "title": 'Required Course',
        "block_type": 'required',
        "credits_needed": 3,
        "sort_order": 1,
        "courses": [
          {
            "subject": 'PHIL',
            "catalog": '210',
            "title": 'Introduction to Deductive Logic',
            "credits": 3.0,
            "is_required": True,
          },
        ],
      },
      {
        "block_key": 'philosophy_major_complementary',
        "title": 'Complementary Courses',
        "block_type": 'multi_group',
        "credits_needed": 33,
        "notes": '33 credits total, of which no more than 9 may be at the 200 level and at least 9 must be at the 400 or 500 level. Only one of PHIL 200 or PHIL 201 may be included.',
        "sort_order": 2,
      },
      {
        "block_key": 'philosophy_major_group_a',
        "title": 'Group A',
        "block_type": 'group',
        "group_name": 'Group A',
        "credits_needed": 3,
        "sort_order": 3,
        "courses": [
          {
            "subject": 'PHIL',
            "catalog": '306',
            "title": 'Philosophy of Mind',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '310',
            "title": 'Intermediate Logic',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '311',
            "title": 'Philosophy of Mathematics',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '341',
            "title": 'Philosophy of Science 1',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '411',
            "title": 'Topics in Philosophy of Logic and Mathematics',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '415',
            "title": 'Philosophy of Language',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '419',
            "title": 'Epistemology',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '421',
            "title": 'Metaphysics',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '441',
            "title": 'Philosophy of Science 2',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '470',
            "title": 'Topics in Contemporary Analytic Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
        ],
      },
      {
        "block_key": 'philosophy_major_group_b',
        "title": 'Group B',
        "block_type": 'group',
        "group_name": 'Group B',
        "credits_needed": 3,
        "sort_order": 4,
        "courses": [
          {
            "subject": 'PHIL',
            "catalog": '375',
            "title": 'Existentialism',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'PHIL',
            "catalog": '474',
            "title": 'Phenomenology',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'PHIL',
            "catalog": '475',
            "title": 'Topics in Contemporary European Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
        ],
      },
      {
        "block_key": 'philosophy_major_group_c_or_d',
        "title": 'Group C or Group D (6 credits, two courses)',
        "block_type": 'choose_credits',
        "credits_needed": 6,
        "notes": '6 credits (two courses) from either Group C or Group D combined.',
        "sort_order": 5,
        "courses": [
          {
            "subject": 'PHIL',
            "catalog": '344',
            "title": 'Medieval and Renaissance Political Theory',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '345',
            "title": 'Greek Political Theory',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '350',
            "title": 'History and Philosophy of Ancient Science',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '353',
            "title": 'The Presocratic Philosophers',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '354',
            "title": 'Plato',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '355',
            "title": 'Aristotle',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '356',
            "title": 'Early Medieval Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '360',
            "title": '17th Century Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '361',
            "title": '18th Century Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '366',
            "title": '18th and Early 19th Century German Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '367',
            "title": '19th Century Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '444',
            "title": 'Early Modern Political Theory',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '445',
            "title": '19th Century Political Theory',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '452',
            "title": 'Later Greek Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '453',
            "title": 'Ancient Metaphysics and Natural Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
          {
            "subject": 'PHIL',
            "catalog": '454',
            "title": 'Ancient Moral Theory',
            "credits": 3.0,
            "choose_from_group": 'Group C/D',
          },
        ],
      },
      {
        "block_key": 'philosophy_major_group_e',
        "title": 'Group E',
        "block_type": 'group',
        "group_name": 'Group E',
        "credits_needed": 3,
        "sort_order": 6,
        "courses": [
          {
            "subject": 'PHIL',
            "catalog": '230',
            "title": 'Introduction to Moral Philosophy 1',
            "credits": 3.0,
            "choose_from_group": 'Group E',
          },
          {
            "subject": 'PHIL',
            "catalog": '237',
            "title": 'Contemporary Moral Issues',
            "credits": 3.0,
            "choose_from_group": 'Group E',
          },
          {
            "subject": 'PHIL',
            "catalog": '240',
            "title": 'Political Philosophy 1',
            "credits": 3.0,
            "choose_from_group": 'Group E',
          },
          {
            "subject": 'PHIL',
            "catalog": '242',
            "title": 'Introduction to Feminist Theory',
            "credits": 3.0,
            "choose_from_group": 'Group E',
          },
        ],
      },
      {
        "block_key": 'philosophy_major_group_f',
        "title": 'Group F',
        "block_type": 'group',
        "group_name": 'Group F',
        "credits_needed": 3,
        "sort_order": 7,
        "courses": [
          {
            "subject": 'PHIL',
            "catalog": '334',
            "title": 'Ethical Theory',
            "credits": 3.0,
            "choose_from_group": 'Group F',
          },
          {
            "subject": 'PHIL',
            "catalog": '343',
            "title": 'Biomedical Ethics',
            "credits": 3.0,
            "choose_from_group": 'Group F',
          },
          {
            "subject": 'PHIL',
            "catalog": '348',
            "title": 'Philosophy of Law 1',
            "credits": 3.0,
            "choose_from_group": 'Group F',
          },
          {
            "subject": 'PHIL',
            "catalog": '427',
            "title": 'Topics in Critical Philosophy of Race',
            "credits": 3.0,
            "choose_from_group": 'Group F',
          },
          {
            "subject": 'PHIL',
            "catalog": '434',
            "title": 'Metaethics',
            "credits": 3.0,
            "choose_from_group": 'Group F',
          },
          {
            "subject": 'PHIL',
            "catalog": '442',
            "title": 'Topics in Feminist Theory',
            "credits": 3.0,
            "choose_from_group": 'Group F',
          },
        ],
      },
      {
        "block_key": 'philosophy_major_additional',
        "title": 'Additional Elective Courses',
        "block_type": 'choose_credits',
        "credits_needed": 15,
        "notes": '15 additional credits from Groups A, B, C, D, E, F or other Philosophy (PHIL) courses. Only one of PHIL 200 (Introduction to Philosophy 1) or PHIL 201 (Introduction to Philosophy 2) may be included. Subject to overall complementary constraints: max 9 credits at 200-level, min 9 credits at 400/500-level.',
        "sort_order": 8,
        "courses": [
          {
            "subject": 'PHIL',
            "catalog": '200',
            "title": 'Introduction to Philosophy 1',
            "credits": 3.0,
            "notes": 'Mutually exclusive with PHIL 201',
          },
          {
            "subject": 'PHIL',
            "catalog": '201',
            "title": 'Introduction to Philosophy 2',
            "credits": 3.0,
            "notes": 'Mutually exclusive with PHIL 200',
          },
        ],
      },
    ],
  },
  {
    "program_key": 'philosophy_minor',
    "name": 'Philosophy – Minor Concentration',
    "program_type": 'minor',
    "faculty": 'Faculty of Arts',
    "total_credits": 18,
    "description": 'An 18-credit introduction to philosophical reasoning, ethics, logic, and history of thought. 18 credits, of which no more than 9 credits may be at the 200 level and at least 3 credits must be at the 400 or 500 level, distributed as follows: 15 credits from Groups A, B, C, D, and E with one course from at least four of the five groups. 3 additional credits from Groups A, B, C, D, and E or from other Philosophy (PHIL) courses.',
    "ecalendar_url": 'https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/philosophy/philosophy-minor-concentration-ba/',
    "blocks": [
      {
        "block_key": 'philosophy_minor_electives',
        "title": 'Complementary Courses (18 credits)',
        "block_type": 'pool_group',
        "credits_needed": 18,
        "notes": '18 credits total, of which no more than 9 credits may be at the 200 level and at least 3 credits must be at the 400 or 500 level. Must include one course from at least four of the five groups.',
        "sort_order": 1,
      },
      {
        "block_key": 'philosophy_minor_group_a',
        "title": 'Group A',
        "block_type": 'group',
        "group_name": 'Group A',
        "notes": 'Ethics and Applied Philosophy',
        "sort_order": 2,
        "courses": [
          {
            "subject": 'PHIL',
            "catalog": '230',
            "title": 'Introduction to Moral Philosophy 1',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '237',
            "title": 'Contemporary Moral Issues',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '240',
            "title": 'Political Philosophy 1',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '242',
            "title": 'Introduction to Feminist Theory',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '334',
            "title": 'Ethical Theory',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '343',
            "title": 'Biomedical Ethics',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '348',
            "title": 'Philosophy of Law 1',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '427',
            "title": 'Topics in Critical Philosophy of Race',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '434',
            "title": 'Metaethics',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
          {
            "subject": 'PHIL',
            "catalog": '442',
            "title": 'Topics in Feminist Theory',
            "credits": 3.0,
            "choose_from_group": 'Group A',
          },
        ],
      },
      {
        "block_key": 'philosophy_minor_group_b',
        "title": 'Group B',
        "block_type": 'group',
        "group_name": 'Group B',
        "notes": 'Logic, Epistemology, Metaphysics, and Philosophy of Science',
        "sort_order": 3,
        "courses": [
          {
            "subject": 'PHIL',
            "catalog": '210',
            "title": 'Introduction to Deductive Logic 1',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'PHIL',
            "catalog": '221',
            "title": 'Introduction to History and Philosophy of Science 2',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'PHIL',
            "catalog": '306',
            "title": 'Philosophy of Mind',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'PHIL',
            "catalog": '310',
            "title": 'Intermediate Logic',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'PHIL',
            "catalog": '311',
            "title": 'Philosophy of Mathematics',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'PHIL',
            "catalog": '341',
            "title": 'Philosophy of Science 1',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'PHIL',
            "catalog": '411',
            "title": 'Topics in Philosophy of Logic and Mathematics',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'PHIL',
            "catalog": '415',
            "title": 'Philosophy of Language',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'PHIL',
            "catalog": '419',
            "title": 'Epistemology',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'PHIL',
            "catalog": '421',
            "title": 'Metaphysics',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'PHIL',
            "catalog": '441',
            "title": 'Philosophy of Science 2',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
          {
            "subject": 'PHIL',
            "catalog": '470',
            "title": 'Topics in Contemporary Analytic Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group B',
          },
        ],
      },
      {
        "block_key": 'philosophy_minor_group_c',
        "title": 'Group C',
        "block_type": 'group',
        "group_name": 'Group C',
        "notes": 'Continental and European Philosophy',
        "sort_order": 4,
        "courses": [
          {
            "subject": 'PHIL',
            "catalog": '375',
            "title": 'Existentialism',
            "credits": 3.0,
            "choose_from_group": 'Group C',
          },
          {
            "subject": 'PHIL',
            "catalog": '474',
            "title": 'Phenomenology',
            "credits": 3.0,
            "choose_from_group": 'Group C',
          },
          {
            "subject": 'PHIL',
            "catalog": '475',
            "title": 'Topics in Contemporary European Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group C',
          },
        ],
      },
      {
        "block_key": 'philosophy_minor_group_d',
        "title": 'Group D',
        "block_type": 'group',
        "group_name": 'Group D',
        "notes": 'Ancient Philosophy',
        "sort_order": 5,
        "courses": [
          {
            "subject": 'PHIL',
            "catalog": '344',
            "title": 'Medieval and Renaissance Political Theory',
            "credits": 3.0,
            "choose_from_group": 'Group D',
          },
          {
            "subject": 'PHIL',
            "catalog": '345',
            "title": 'Greek Political Theory',
            "credits": 3.0,
            "choose_from_group": 'Group D',
          },
          {
            "subject": 'PHIL',
            "catalog": '350',
            "title": 'History and Philosophy of Ancient Science',
            "credits": 3.0,
            "choose_from_group": 'Group D',
          },
          {
            "subject": 'PHIL',
            "catalog": '353',
            "title": 'The Presocratic Philosophers',
            "credits": 3.0,
            "choose_from_group": 'Group D',
          },
          {
            "subject": 'PHIL',
            "catalog": '354',
            "title": 'Plato',
            "credits": 3.0,
            "choose_from_group": 'Group D',
          },
          {
            "subject": 'PHIL',
            "catalog": '355',
            "title": 'Aristotle',
            "credits": 3.0,
            "choose_from_group": 'Group D',
          },
          {
            "subject": 'PHIL',
            "catalog": '356',
            "title": 'Early Medieval Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group D',
          },
          {
            "subject": 'PHIL',
            "catalog": '452',
            "title": 'Later Greek Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group D',
          },
          {
            "subject": 'PHIL',
            "catalog": '453',
            "title": 'Ancient Metaphysics and Natural Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group D',
          },
          {
            "subject": 'PHIL',
            "catalog": '454',
            "title": 'Ancient Moral Theory',
            "credits": 3.0,
            "choose_from_group": 'Group D',
          },
        ],
      },
      {
        "block_key": 'philosophy_minor_group_e',
        "title": 'Group E',
        "block_type": 'group',
        "group_name": 'Group E',
        "notes": 'Modern Philosophy and History of Philosophy',
        "sort_order": 6,
        "courses": [
          {
            "subject": 'PHIL',
            "catalog": '360',
            "title": '17th Century Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group E',
          },
          {
            "subject": 'PHIL',
            "catalog": '361',
            "title": '18th Century Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group E',
          },
          {
            "subject": 'PHIL',
            "catalog": '366',
            "title": '18th and Early 19th Century German Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group E',
          },
          {
            "subject": 'PHIL',
            "catalog": '367',
            "title": '19th Century Philosophy',
            "credits": 3.0,
            "choose_from_group": 'Group E',
          },
          {
            "subject": 'PHIL',
            "catalog": '444',
            "title": 'Early Modern Political Theory',
            "credits": 3.0,
            "choose_from_group": 'Group E',
          },
          {
            "subject": 'PHIL',
            "catalog": '445',
            "title": '19th Century Political Theory',
            "credits": 3.0,
            "choose_from_group": 'Group E',
          },
        ],
      },
    ],
  },
]
