"""
McGill Faculty of Science – Degree Requirements Part 2
Chemistry, Biology, Biochemistry, Microbiology & Immunology
"""

SCIENCE_PROGRAMS_PART2 = [

  # ══════════════════════════════════════════════════════════════════════
  #  CHEMISTRY
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "chemistry_minor_bsc",
    "name": "Chemistry Minor (B.Sc.) (24 credits)",
    "program_type": "minor",
    "faculty": "Faculty of Science",
    "total_credits": 24,
    "description": "May be combined with any primary program in the Faculty of Science other than Chemistry programs.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/chemistry/chemistry-minor-bsc/",
    "blocks": [
      {
        "block_key": "chem_minor_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 18,
        "courses_needed": None,
        "group_name": None,
        "notes": "CHEM 110/120 may be replaced by CHEM 115/123 (Science stream) for students with advanced standing.",
        "sort_order": 1,
        "courses": [
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "120", "title": "General Chemistry 2",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "213", "title": "Introductory Organic Chemistry 2",     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "222", "title": "Introductory Analytical Chemistry",    "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "314", "title": "Physical Chemistry: Thermodynamics",   "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "chem_minor_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 6,
        "courses_needed": None,
        "group_name": None,
        "notes": "6 credits from CHEM 300+.",
        "sort_order": 2,
        "courses": [
          {"subject": "CHEM", "catalog": "310", "title": "Advanced Inorganic Chemistry",         "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "315", "title": "Physical Chemistry: Quantum Mechanics","credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "322", "title": "Organic Chemistry 3",                  "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "323", "title": "Organic Chemistry 4",                  "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "325", "title": "Analytical Chemistry",                 "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "340", "title": "Computational Chemistry",              "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "402", "title": "Structural Biochemistry",              "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "chemistry_major_bsc",
    "name": "Chemistry Major (B.Sc.) (66 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 66,
    "description": "Provides a broad and thorough foundation in all major areas of chemistry including organic, inorganic, physical, and analytical chemistry.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/chemistry/chemistry-major-bsc/",
    "blocks": [
      {
        "block_key": "chem_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 48,
        "courses_needed": None,
        "group_name": None,
        "notes": "CHEM 115/123 may substitute CHEM 110/120 for students with CEGEP advanced standing.",
        "sort_order": 1,
        "courses": [
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "120", "title": "General Chemistry 2",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "213", "title": "Introductory Organic Chemistry 2",     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "222", "title": "Introductory Analytical Chemistry",    "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "310", "title": "Advanced Inorganic Chemistry",         "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "314", "title": "Physical Chemistry: Thermodynamics",   "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "315", "title": "Physical Chemistry: Quantum Mechanics","credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "322", "title": "Organic Chemistry 3",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "323", "title": "Organic Chemistry 4",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "325", "title": "Analytical Chemistry",                 "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "391", "title": "Laboratory Chemistry 3",               "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "481", "title": "Laboratory Chemistry 4",               "credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "222", "title": "Calculus 3",                            "credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "315", "title": "Ordinary Differential Equations",       "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "101", "title": "Introductory Physics – Mechanics",      "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "chem_major_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 18,
        "courses_needed": None,
        "group_name": None,
        "notes": "18 credits from CHEM 300+ or approved courses in related sciences.",
        "sort_order": 2,
        "courses": [
          {"subject": "CHEM", "catalog": "340", "title": "Computational Chemistry",              "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "402", "title": "Structural Biochemistry",              "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "404", "title": "Medicinal Chemistry",                  "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "410", "title": "Organometallic Chemistry",             "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "416", "title": "Physical Organic Chemistry",           "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "417", "title": "Polymer Chemistry",                    "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "420", "title": "Advanced Analytical Chemistry",        "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "424", "title": "Atmospheric Chemistry",                "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "430", "title": "Solid State Chemistry",                "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "450", "title": "Advanced Physical Chemistry",          "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "chemistry_honours_bsc",
    "name": "Chemistry Honours (B.Sc.) (72 credits)",
    "program_type": "honours",
    "faculty": "Faculty of Science",
    "total_credits": 72,
    "description": "Designed for students with high aptitude in chemistry who intend to pursue graduate studies or a research career. Includes a research project.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/chemistry/chemistry-honours-bsc/",
    "blocks": [
      {
        "block_key": "chem_hon_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 57,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "120", "title": "General Chemistry 2",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "213", "title": "Introductory Organic Chemistry 2",     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "222", "title": "Introductory Analytical Chemistry",    "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "310", "title": "Advanced Inorganic Chemistry",         "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "314", "title": "Physical Chemistry: Thermodynamics",   "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "315", "title": "Physical Chemistry: Quantum Mechanics","credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "322", "title": "Organic Chemistry 3",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "323", "title": "Organic Chemistry 4",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "325", "title": "Analytical Chemistry",                 "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "391", "title": "Laboratory Chemistry 3",               "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "481", "title": "Laboratory Chemistry 4",               "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "490", "title": "Research Project 1",                   "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "491", "title": "Research Project 2",                   "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "495", "title": "Seminar in Chemistry",                 "credits": 1, "is_required": True},
          {"subject": "MATH", "catalog": "222", "title": "Calculus 3",                            "credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "315", "title": "Ordinary Differential Equations",       "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "101", "title": "Introductory Physics – Mechanics",      "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "chem_hon_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 15,
        "courses_needed": None,
        "group_name": None,
        "notes": "15 credits from CHEM 300+. Max 6 credits from research (490/491).",
        "sort_order": 2,
        "courses": [
          {"subject": "CHEM", "catalog": "340", "title": "Computational Chemistry",              "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "402", "title": "Structural Biochemistry",              "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "404", "title": "Medicinal Chemistry",                  "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "410", "title": "Organometallic Chemistry",             "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "416", "title": "Physical Organic Chemistry",           "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "417", "title": "Polymer Chemistry",                    "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "420", "title": "Advanced Analytical Chemistry",        "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "424", "title": "Atmospheric Chemistry",                "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "430", "title": "Solid State Chemistry",                "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "450", "title": "Advanced Physical Chemistry",          "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  # ══════════════════════════════════════════════════════════════════════
  #  BIOLOGY
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "biology_liberal_bsc",
    "name": "Biology – Liberal Program Core Science Component (B.Sc.) (47 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 47,
    "description": "Provides an introduction to cell/molecular biology, organismal biology, and evolutionary biology combined with supporting courses in chemistry, physics, and mathematics.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/biology/biology-liberal-program-core-science-component-bsc/",
    "blocks": [
      {
        "block_key": "biol_lib_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 36,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "111", "title": "Principles of Biology 1 (Organismal)", "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "112", "title": "Principles of Biology 2 (Cell/Molecular)", "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",          "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "202", "title": "Introduction to Evolution",            "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "300", "title": "Biostatistics",                        "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "120", "title": "General Chemistry 2",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "101", "title": "Introductory Physics – Mechanics",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "102", "title": "Introductory Physics – Electromagnetism","credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "139", "title": "Calculus (Science Program)",           "credits": 4, "is_required": True},
        ],
      },
      {
        "block_key": "biol_lib_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 11,
        "courses_needed": None,
        "group_name": None,
        "notes": "11 credits from BIOL 300+ or approved supporting courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "BIOL", "catalog": "301", "title": "Population Biology",                   "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "302", "title": "Ecology",                              "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "304", "title": "Genetics",                             "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "306", "title": "Developmental Biology",                "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "308", "title": "Comparative Animal Physiology",        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "311", "title": "Plant Biology",                        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "317", "title": "Microbiology",                         "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "373", "title": "Neurobiology",                         "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "376", "title": "Immunology",                           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "385", "title": "Marine Biology",                       "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "biology_major_bsc",
    "name": "Biology Major (B.Sc.) (63 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 63,
    "description": "Covers cell/molecular biology, genetics, evolution, ecology, and physiology. Students may focus on Cell/Molecular or Organismal biology through choice of complementary courses.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/biology/biology-major-bsc/",
    "blocks": [
      {
        "block_key": "biol_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 39,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "111", "title": "Principles of Biology 1 (Organismal)", "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "112", "title": "Principles of Biology 2 (Cell/Molecular)", "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",          "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "202", "title": "Introduction to Evolution",            "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "300", "title": "Biostatistics",                        "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "304", "title": "Genetics",                             "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "120", "title": "General Chemistry 2",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "101", "title": "Introductory Physics – Mechanics",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "102", "title": "Introductory Physics – Electromagnetism","credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "139", "title": "Calculus (Science Program)",           "credits": 4, "is_required": True},
        ],
      },
      {
        "block_key": "biol_major_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 24,
        "courses_needed": None,
        "group_name": None,
        "notes": "24 credits from BIOL 300+. At least 12 must be from 400-level BIOL courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "BIOL", "catalog": "301", "title": "Population Biology",                   "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "302", "title": "Ecology",                              "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "306", "title": "Developmental Biology",                "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "307", "title": "Techniques in Molecular Biology",      "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "308", "title": "Comparative Animal Physiology",        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "311", "title": "Plant Biology",                        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "317", "title": "Microbiology",                         "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "373", "title": "Neurobiology",                         "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "376", "title": "Immunology",                           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "385", "title": "Marine Biology",                       "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                   "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "404", "title": "Functional Genomics",                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "411", "title": "Cell Regulation and Signaling",        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "426", "title": "Plant Physiology",                     "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "430", "title": "Evolutionary Genetics",                "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "432", "title": "Conservation Biology",                 "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "441", "title": "Population Genetics",                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "449", "title": "Animal Behaviour",                     "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "465", "title": "Biodiversity and Macroecology",        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "478", "title": "Developmental Genetics",               "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "biology_honours_bsc",
    "name": "Biology Honours (B.Sc.) (72 credits)",
    "program_type": "honours",
    "faculty": "Faculty of Science",
    "total_credits": 72,
    "description": "Provides advanced training in biology for students who plan to pursue graduate studies or research. Includes an independent research project.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/biology/biology-honours-bsc/",
    "blocks": [
      {
        "block_key": "biol_hon_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 51,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "111", "title": "Principles of Biology 1 (Organismal)", "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "112", "title": "Principles of Biology 2 (Cell/Molecular)", "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",          "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "202", "title": "Introduction to Evolution",            "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "300", "title": "Biostatistics",                        "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "304", "title": "Genetics",                             "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "446", "title": "Research Project",                     "credits": 6, "is_required": True},
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "120", "title": "General Chemistry 2",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "101", "title": "Introductory Physics – Mechanics",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "102", "title": "Introductory Physics – Electromagnetism","credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "139", "title": "Calculus (Science Program)",           "credits": 4, "is_required": True},
        ],
      },
      {
        "block_key": "biol_hon_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 21,
        "courses_needed": None,
        "group_name": None,
        "notes": "21 credits from BIOL 300+. At least 12 credits from BIOL 400+.",
        "sort_order": 2,
        "courses": [
          {"subject": "BIOL", "catalog": "301", "title": "Population Biology",                   "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "302", "title": "Ecology",                              "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "306", "title": "Developmental Biology",                "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "307", "title": "Techniques in Molecular Biology",      "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "308", "title": "Comparative Animal Physiology",        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "311", "title": "Plant Biology",                        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "317", "title": "Microbiology",                         "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "373", "title": "Neurobiology",                         "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "376", "title": "Immunology",                           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                   "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "404", "title": "Functional Genomics",                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "411", "title": "Cell Regulation and Signaling",        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "430", "title": "Evolutionary Genetics",                "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "432", "title": "Conservation Biology",                 "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "441", "title": "Population Genetics",                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "449", "title": "Animal Behaviour",                     "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "465", "title": "Biodiversity and Macroecology",        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "478", "title": "Developmental Genetics",               "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  # ══════════════════════════════════════════════════════════════════════
  #  BIOCHEMISTRY
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "biochemistry_liberal_bsc",
    "name": "Biochemistry – Liberal Program Core Science Component (B.Sc.) (47 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 47,
    "description": "Provides a foundation in biochemistry with supporting courses in biology, chemistry, physics, and mathematics.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/biochemistry/biochemistry-liberal-program-core-component-bsc/",
    "blocks": [
      {
        "block_key": "bioc_lib_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 47,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "112", "title": "Principles of Biology 2 (Cell/Molecular)", "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",          "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "311", "title": "Biochemistry 1",                       "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "312", "title": "Biochemistry 2",                       "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "120", "title": "General Chemistry 2",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "213", "title": "Introductory Organic Chemistry 2",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "101", "title": "Introductory Physics – Mechanics",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "102", "title": "Introductory Physics – Electromagnetism","credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "139", "title": "Calculus (Science Program)",           "credits": 4, "is_required": True},
          {"subject": "MATH", "catalog": "133", "title": "Vectors, Matrices and Geometry",       "credits": 3, "is_required": True},
        ],
      },
    ],
  },

  {
    "program_key": "biochemistry_major_bsc",
    "name": "Biochemistry Major (B.Sc.) (63 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 63,
    "description": "Integrates molecular biology, cell biology, and chemistry to understand biological processes at the molecular level.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/biochemistry/biochemistry-major-bsc/",
    "blocks": [
      {
        "block_key": "bioc_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 45,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "112", "title": "Principles of Biology 2 (Cell/Molecular)","credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",          "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "300", "title": "Biostatistics",                        "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "311", "title": "Biochemistry 1",                       "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "312", "title": "Biochemistry 2",                       "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "313", "title": "Biochemistry Laboratory",              "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "120", "title": "General Chemistry 2",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "213", "title": "Introductory Organic Chemistry 2",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "101", "title": "Introductory Physics – Mechanics",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "102", "title": "Introductory Physics – Electromagnetism","credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "139", "title": "Calculus (Science Program)",           "credits": 4, "is_required": True},
          {"subject": "MATH", "catalog": "133", "title": "Vectors, Matrices and Geometry",       "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "bioc_major_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 18,
        "courses_needed": None,
        "group_name": None,
        "notes": "18 credits from approved BIOC, BIOL, CHEM, and related courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "BIOC", "catalog": "411", "title": "Biochemistry 3",                       "credits": 3, "is_required": False},
          {"subject": "BIOC", "catalog": "412", "title": "Biochemistry 4",                       "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "304", "title": "Genetics",                             "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "307", "title": "Techniques in Molecular Biology",      "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                   "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "404", "title": "Functional Genomics",                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "411", "title": "Cell Regulation and Signaling",        "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "314", "title": "Physical Chemistry: Thermodynamics",   "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "315", "title": "Physical Chemistry: Quantum Mechanics","credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "322", "title": "Organic Chemistry 3",                  "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "402", "title": "Structural Biochemistry",              "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "404", "title": "Medicinal Chemistry",                  "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "biochemistry_honours_bsc",
    "name": "Biochemistry Honours (B.Sc.) (69 credits)",
    "program_type": "honours",
    "faculty": "Faculty of Science",
    "total_credits": 69,
    "description": "For students planning to pursue graduate study or a research career in biochemistry, molecular biology, or related fields.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/biochemistry/biochemistry-honours-bsc/",
    "blocks": [
      {
        "block_key": "bioc_hon_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 57,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "112", "title": "Principles of Biology 2 (Cell/Molecular)","credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",          "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "300", "title": "Biostatistics",                        "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "304", "title": "Genetics",                             "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "311", "title": "Biochemistry 1",                       "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "312", "title": "Biochemistry 2",                       "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "313", "title": "Biochemistry Laboratory",              "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "411", "title": "Biochemistry 3",                       "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "412", "title": "Biochemistry 4",                       "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "413", "title": "Advanced Biochemistry Laboratory",     "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "440", "title": "Honours Research Project",             "credits": 6, "is_required": True},
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "120", "title": "General Chemistry 2",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "213", "title": "Introductory Organic Chemistry 2",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "101", "title": "Introductory Physics – Mechanics",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "102", "title": "Introductory Physics – Electromagnetism","credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "139", "title": "Calculus (Science Program)",           "credits": 4, "is_required": True},
        ],
      },
      {
        "block_key": "bioc_hon_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 12,
        "courses_needed": None,
        "group_name": None,
        "notes": "12 credits from approved upper-level BIOC, BIOL, or CHEM courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "BIOL", "catalog": "307", "title": "Techniques in Molecular Biology",      "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                   "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "404", "title": "Functional Genomics",                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "411", "title": "Cell Regulation and Signaling",        "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "314", "title": "Physical Chemistry: Thermodynamics",   "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "402", "title": "Structural Biochemistry",              "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "404", "title": "Medicinal Chemistry",                  "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  # ══════════════════════════════════════════════════════════════════════
  #  MICROBIOLOGY & IMMUNOLOGY
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "microbiology_immunology_major_bsc",
    "name": "Microbiology and Immunology Major (B.Sc.) (63 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 63,
    "description": "Studies microorganisms (bacteria, viruses, fungi, parasites) and the immune system, with laboratory work in microbial techniques.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/microbiology-immunology/microbiology-immunology-major-bsc/",
    "blocks": [
      {
        "block_key": "mibi_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 45,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "112", "title": "Principles of Biology 2 (Cell/Molecular)","credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",          "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "300", "title": "Biostatistics",                        "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "303", "title": "Virology",                             "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "304", "title": "Genetics",                             "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "307", "title": "Techniques in Molecular Biology",      "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "376", "title": "Immunology",                           "credits": 3, "is_required": True},
          {"subject": "MIBI", "catalog": "331", "title": "Microbiology Laboratory",              "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "120", "title": "General Chemistry 2",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "139", "title": "Calculus (Science Program)",           "credits": 4, "is_required": True},
          {"subject": "PHYS", "catalog": "101", "title": "Introductory Physics – Mechanics",     "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "mibi_major_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 18,
        "courses_needed": None,
        "group_name": None,
        "notes": "18 credits from MIBI 400+ or approved BIOL 400+ courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "MIBI", "catalog": "411", "title": "Medical Microbiology",                 "credits": 3, "is_required": False},
          {"subject": "MIBI", "catalog": "414", "title": "Bacterial Pathogenesis",               "credits": 3, "is_required": False},
          {"subject": "MIBI", "catalog": "420", "title": "Advanced Immunology",                  "credits": 3, "is_required": False},
          {"subject": "MIBI", "catalog": "425", "title": "Molecular Virology",                   "credits": 3, "is_required": False},
          {"subject": "MIBI", "catalog": "430", "title": "Host-Pathogen Interactions",           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                   "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "404", "title": "Functional Genomics",                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "411", "title": "Cell Regulation and Signaling",        "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "microbiology_immunology_honours_bsc",
    "name": "Microbiology and Immunology Honours (B.Sc.) (72 credits)",
    "program_type": "honours",
    "faculty": "Faculty of Science",
    "total_credits": 72,
    "description": "Provides advanced training in microbiology and immunology for students planning graduate study or research careers.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/microbiology-immunology/microbiology-immunology-honours-bsc/",
    "blocks": [
      {
        "block_key": "mibi_hon_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 54,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "112", "title": "Principles of Biology 2 (Cell/Molecular)","credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",          "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "300", "title": "Biostatistics",                        "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "303", "title": "Virology",                             "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "304", "title": "Genetics",                             "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "307", "title": "Techniques in Molecular Biology",      "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "376", "title": "Immunology",                           "credits": 3, "is_required": True},
          {"subject": "MIBI", "catalog": "331", "title": "Microbiology Laboratory",              "credits": 3, "is_required": True},
          {"subject": "MIBI", "catalog": "420", "title": "Advanced Immunology",                  "credits": 3, "is_required": True},
          {"subject": "MIBI", "catalog": "425", "title": "Molecular Virology",                   "credits": 3, "is_required": True},
          {"subject": "MIBI", "catalog": "444", "title": "Honours Research Project",             "credits": 6, "is_required": True},
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "120", "title": "General Chemistry 2",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "139", "title": "Calculus (Science Program)",           "credits": 4, "is_required": True},
          {"subject": "PHYS", "catalog": "101", "title": "Introductory Physics – Mechanics",     "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "mibi_hon_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 18,
        "courses_needed": None,
        "group_name": None,
        "notes": "18 credits from MIBI 400+ or approved upper-level biology/biochemistry courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "MIBI", "catalog": "411", "title": "Medical Microbiology",                 "credits": 3, "is_required": False},
          {"subject": "MIBI", "catalog": "414", "title": "Bacterial Pathogenesis",               "credits": 3, "is_required": False},
          {"subject": "MIBI", "catalog": "430", "title": "Host-Pathogen Interactions",           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                   "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "404", "title": "Functional Genomics",                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "411", "title": "Cell Regulation and Signaling",        "credits": 3, "is_required": False},
          {"subject": "BIOC", "catalog": "411", "title": "Biochemistry 3",                       "credits": 3, "is_required": False},
          {"subject": "BIOC", "catalog": "412", "title": "Biochemistry 4",                       "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  # ══════════════════════════════════════════════════════════════════════
  #  ANATOMY & CELL BIOLOGY
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "anatomy_cell_biology_liberal_bsc",
    "name": "Anatomy and Cell Biology – Liberal Program Core Science Component (B.Sc.) (48 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 48,
    "description": "Introduction to human gross anatomy, histology, cell biology, and neuroscience.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/anatomy-cell-biology/anatomy-cell-biology-liberal-program-core-component-bsc/",
    "blocks": [
      {
        "block_key": "anat_lib_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 48,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "ANAT", "catalog": "212", "title": "Gross Anatomy",                        "credits": 3, "is_required": True},
          {"subject": "ANAT", "catalog": "261", "title": "Principles of Cell Biology",           "credits": 3, "is_required": True},
          {"subject": "ANAT", "catalog": "313", "title": "Neuroscience 1",                       "credits": 3, "is_required": True},
          {"subject": "ANAT", "catalog": "321", "title": "Histology",                            "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "112", "title": "Principles of Biology 2 (Cell/Molecular)","credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",          "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "300", "title": "Biostatistics",                        "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "120", "title": "General Chemistry 2",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "101", "title": "Introductory Physics – Mechanics",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "102", "title": "Introductory Physics – Electromagnetism","credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "139", "title": "Calculus (Science Program)",           "credits": 4, "is_required": True},
        ],
      },
    ],
  },

  {
    "program_key": "anatomy_cell_biology_major_bsc",
    "name": "Anatomy and Cell Biology Major (B.Sc.) (67 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 67,
    "description": "Studies human anatomy and cell biology with laboratory components in histology and gross anatomy dissection.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/anatomy-cell-biology/anatomy-cell-biology-major-bsc/",
    "blocks": [
      {
        "block_key": "anat_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 55,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "ANAT", "catalog": "212", "title": "Gross Anatomy",                        "credits": 3, "is_required": True},
          {"subject": "ANAT", "catalog": "261", "title": "Principles of Cell Biology",           "credits": 3, "is_required": True},
          {"subject": "ANAT", "catalog": "313", "title": "Neuroscience 1",                       "credits": 3, "is_required": True},
          {"subject": "ANAT", "catalog": "321", "title": "Histology",                            "credits": 3, "is_required": True},
          {"subject": "ANAT", "catalog": "322", "title": "Advanced Cell Biology",                "credits": 3, "is_required": True},
          {"subject": "ANAT", "catalog": "411", "title": "Advanced Gross Anatomy",               "credits": 3, "is_required": True},
          {"subject": "ANAT", "catalog": "417", "title": "Advanced Histology",                   "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "112", "title": "Principles of Biology 2 (Cell/Molecular)","credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",          "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "300", "title": "Biostatistics",                        "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "304", "title": "Genetics",                             "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "120", "title": "General Chemistry 2",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "101", "title": "Introductory Physics – Mechanics",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "102", "title": "Introductory Physics – Electromagnetism","credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "139", "title": "Calculus (Science Program)",           "credits": 4, "is_required": True},
        ],
      },
      {
        "block_key": "anat_major_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 12,
        "courses_needed": None,
        "group_name": None,
        "notes": "12 credits from ANAT 400+ or approved related courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "ANAT", "catalog": "415", "title": "Developmental Anatomy",               "credits": 3, "is_required": False},
          {"subject": "ANAT", "catalog": "420", "title": "Neuroscience 2",                      "credits": 3, "is_required": False},
          {"subject": "ANAT", "catalog": "430", "title": "Special Topics in Anatomy",           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "306", "title": "Developmental Biology",               "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "411", "title": "Cell Regulation and Signaling",       "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "311", "title": "Mammalian Physiology 1",              "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "312", "title": "Mammalian Physiology 2",              "credits": 3, "is_required": False},
        ],
      },
    ],
  },

]  # END SCIENCE_PROGRAMS_PART2
